# ROOST_METHOD_HASH=parse_usernames_0092ae2774
# ROOST_METHOD_SIG_HASH=parse_usernames_86e81cab01

# NB: existing tests detected for this symbol.
#
# Hand-written test(s) found (no ROOST_METHOD_HASH header):
#   - tests/test_checking.py
# This file was generated ALONGSIDE those — the user's
# tests are kept untouched. The scenarios here may
# differ from what the hand-written file covers.

"""Tests for `maigret.checking.parse_usernames`.

Auto-generated by roost-pytest. Re-generate when the source
changes; see the run report for generation details.
"""
# Source: maigret/checking.py:1231-1246
# Scenarios:
#   - [happy_path] empty_input: Verify that an empty input dictionary returns an empty result dictionary.
#   - [happy_path] mixed_types_and_precedence: Verify handling of mixed input types and ensure that specific supported IDs take precedence over generic 'username' labels for the same value.
#   - [edge_case] usernames_non_list_literal: Verify that a 'usernames' key with a valid Python literal that is not a list (e.g., a dict) is ignored.
#   - [error_path] usernames_already_list_value: Verify that if the value for a 'usernames' key is already a list object (not a string), ast.literal_eval fails, a warning is logged, and the function continues.
#   - [happy_path] multiple_generic_usernames: Verify that multiple keys containing 'username' (but not 'usernames') are all correctly parsed.

import sys
from unittest.mock import Mock

# Mock missing dependencies to allow importing maigret.checking
mock_modules = [
    'aiodns',
    'alive_progress',
    'aiohttp',
    'aiohttp.client_exceptions',
    'python_socks',
    'socid_extractor',
    'curl_cffi',
    'curl_cffi.requests',
    'colorama',
    'xmind',
    'jinja2',
    'requests',
    'cloudscraper',
]
for mod in mock_modules:
    if mod not in sys.modules:
        sys.modules[mod] = Mock()

import pytest
from maigret.checking import parse_usernames

@pytest.mark.generated
@pytest.mark.happy_path
def test_empty_input():
    """Verify that an empty input dictionary returns an empty result dictionary."""
    logger = Mock()
    result = parse_usernames({}, logger)
    assert result == {}

@pytest.mark.generated
@pytest.mark.happy_path
def test_mixed_types_and_precedence():
    """Verify handling of mixed input types and ensure that specific supported IDs take precedence over generic 'username' labels for the same value."""
    logger = Mock()
    # Note: The order of keys in the dictionary matters for the current implementation.
    # 'profile_username' is processed first, setting 'alice' -> 'username'.
    # 'vk_id' is processed second, overwriting 'alice' -> 'vk_id'.
    input_data = {
        "profile_username": "alice",
        "vk_id": "alice",
        "other_usernames": "['bob', 'charlie']"
    }
    result = parse_usernames(input_data, logger)
    assert result == {"alice": "vk_id", "bob": "username", "charlie": "username"}

@pytest.mark.generated
@pytest.mark.edge_case
def test_usernames_non_list_literal():
    """Verify that a 'usernames' key with a valid Python literal that is not a list (e.g., a dict) is ignored."""
    logger = Mock()
    input_data = {"other_usernames": "{'not': 'a_list'}"}
    result = parse_usernames(input_data, logger)
    assert result == {}

@pytest.mark.generated
@pytest.mark.error_path
def test_usernames_already_list_value():
    """Verify that if the value for a 'usernames' key is already a list object (not a string), ast.literal_eval fails, a warning is logged, and the function continues."""
    logger = Mock()
    input_data = {"other_usernames": ["already", "a", "list"]}
    result = parse_usernames(input_data, logger)
    assert result == {}
    assert logger.warning.called

@pytest.mark.generated
@pytest.mark.happy_path
def test_multiple_generic_usernames():
    """Verify that multiple keys containing 'username' (but not 'usernames') are all correctly parsed."""
    logger = Mock()
    input_data = {"u1_username": "alice", "u2_username": "bob"}
    result = parse_usernames(input_data, logger)
    assert result == {"alice": "username", "bob": "username"}
