# ROOST_METHOD_HASH=BAD_CHARS_407003f3b7
# ROOST_METHOD_SIG_HASH=BAD_CHARS_407003f3b7

"""Tests for `maigret.checking.BAD_CHARS`.

Auto-generated by roost-pytest. Re-generate when the source
changes; see the run report for generation details.
"""
# Source: maigret/checking.py:48-48
# Scenarios:
#   - [happy_path] bad_chars_content: Verify that BAD_CHARS is a string and contains the expected character '#'.
#   - [happy_path] username_with_bad_char_detected: Verify that a username containing '#' is correctly identified as having unsupported characters using the logic from maigret.py.
#   - [happy_path] valid_username_not_flagged: Verify that a valid username without '#' does not trigger the unsupported characters logic.
#   - [edge_case] empty_username_not_flagged: Verify that an empty username does not trigger the unsupported characters logic.

import sys
from unittest.mock import MagicMock

# Mock missing dependencies before importing maigret.checking
for module in [
    'aiodns', 'alive_progress', 'socid_extractor', 'python_socks',
    'python_socks._errors', 'aiohttp_socks', 'colorama', 'requests',
    'aiohttp', 'aiohttp.client_exceptions', 'xmind', 'jinja2', 'pandas',
    'networkx', 'matplotlib', 'fpdf', 'markdown', 'yaml', 'cloudscraper',
    'curl_cffi', 'curl_cffi.requests'
]:
    if module not in sys.modules:
        sys.modules[module] = MagicMock()

import pytest
from maigret.checking import BAD_CHARS

@pytest.mark.generated
@pytest.mark.happy_path
def test_bad_chars_content():
    """Verify that BAD_CHARS is a string and contains the expected character '#'."""
    assert isinstance(BAD_CHARS, str)
    assert "#" in BAD_CHARS

@pytest.mark.generated
@pytest.mark.happy_path
def test_username_with_bad_char_detected():
    """Verify that a username containing '#' is correctly identified as having unsupported characters using the logic from maigret.py."""
    username = "user#name"
    result = set(BAD_CHARS).intersection(set(username))
    assert len(result) > 0
    assert "#" in result

@pytest.mark.generated
@pytest.mark.happy_path
def test_valid_username_not_flagged():
    """Verify that a valid username without '#' does not trigger the unsupported characters logic."""
    username = "valid_username_123"
    result = set(BAD_CHARS).intersection(set(username))
    assert len(result) == 0

@pytest.mark.generated
@pytest.mark.edge_case
def test_empty_username_not_flagged():
    """Verify that an empty username does not trigger the unsupported characters logic."""
    username = ""
    result = set(BAD_CHARS).intersection(set(username))
    assert len(result) == 0
