# ROOST_METHOD_HASH=debug_ip_request_97c6ec6168
# ROOST_METHOD_SIG_HASH=debug_ip_request_0b318bdd10

"""Tests for `maigret.checking.debug_ip_request`.

Auto-generated by roost-pytest. Re-generate when the source
changes; see the run report for generation details.
"""
# Source: maigret/checking.py:726-732
# Scenarios:
#   - [happy_path] happy_path_success: Verify that a successful IP request logs the IP address correctly.
#   - [edge_case] ip_with_whitespace: Verify that the IP address is stripped of whitespace before logging.
#   - [error_path] request_error_logging: Verify that a failed request logs the error type and description.
#   - [regression] empty_ip_no_error_bug: Verify behavior when the IP is empty and no error is provided (currently triggers a bug).

import sys
from unittest.mock import Mock, AsyncMock

# Mock missing dependencies and submodules to avoid import errors
for mod in [
    'aiodns', 'alive_progress', 'python_socks', 'python_socks._errors',
    'socid_extractor', 'colorama', 'requests', 'cloudscraper',
    'requests_futures', 'requests_futures.sessions', 'torrequest',
    'xmind', 'jinja2', 'pandas', 'openpyxl', 'odf'
]:
    sys.modules[mod] = Mock()

# Mock submodules that are not needed for this test but cause import issues
sys.modules['maigret.maigret'] = Mock()
sys.modules['maigret.notify'] = Mock()
sys.modules['maigret.report'] = Mock()

import pytest
import asyncio
from maigret.checking import debug_ip_request
from maigret.errors import CheckError

@pytest.mark.generated
@pytest.mark.happy_path
def test_happy_path_success():
    """Verify that a successful IP request logs the IP address correctly."""
    async def _t():
        checker = AsyncMock()
        # prepare is called as a regular function, not awaited
        checker.prepare = Mock()
        checker.check.return_value = ("1.2.3.4", 200, None)
        logger = Mock()
        
        await debug_ip_request(checker, logger)
        
        checker.prepare.assert_called_once_with(url="https://icanhazip.com")
        logger.debug.assert_called_with("My IP is: 1.2.3.4")
    
    asyncio.run(_t())

@pytest.mark.generated
@pytest.mark.edge_case
def test_ip_with_whitespace():
    """Verify that the IP address is stripped of whitespace before logging."""
    async def _t():
        checker = AsyncMock()
        checker.prepare = Mock()
        checker.check.return_value = ("  1.2.3.4  \n", 200, None)
        logger = Mock()
        
        await debug_ip_request(checker, logger)
        
        logger.debug.assert_called_with("My IP is: 1.2.3.4")
    
    asyncio.run(_t())

@pytest.mark.generated
@pytest.mark.error_path
def test_request_error_logging():
    """Verify that a failed request logs the error type and description."""
    async def _t():
        checker = AsyncMock()
        checker.prepare = Mock()
        checker.check.return_value = (None, 0, CheckError("Connection failure", "timeout"))
        logger = Mock()
        
        await debug_ip_request(checker, logger)
        
        logger.debug.assert_called_with("IP requesting Connection failure: timeout")
    
    asyncio.run(_t())

@pytest.mark.generated
@pytest.mark.regression
def test_empty_ip_no_error_bug():
    """Verify behavior when the IP is empty and no error is provided (currently triggers a bug)."""
    async def _t():
        checker = AsyncMock()
        checker.prepare = Mock()
        checker.check.return_value = ("", 200, None)
        logger = Mock()
        
        with pytest.raises(AttributeError):
            await debug_ip_request(checker, logger)
            
    asyncio.run(_t())
