# ROOST_METHOD_HASH=debug_response_logging_3ca895984c
# ROOST_METHOD_SIG_HASH=debug_response_logging_25833a102b

# NB: existing tests detected for this symbol.
#
# Hand-written test(s) found (no ROOST_METHOD_HASH header):
#   - tests/test_checking.py
# This file was generated ALONGSIDE those — the user's
# tests are kept untouched. The scenarios here may
# differ from what the hand-written file covers.

"""Tests for `maigret.checking.debug_response_logging`.

Auto-generated by roost-pytest. Re-generate when the source
changes; see the run report for generation details.
"""
# Source: maigret/checking.py:334-339
# Scenarios:
#   - [happy_path] append_multiple_entries: Verify that multiple calls to debug_response_logging append to the same debug.log file.
#   - [happy_path] html_content_logging: Verify that html_text is correctly logged with the 'response:' prefix when provided.
#   - [edge_case] empty_html_content_omission: Verify that the 'response:' line is omitted from the log when html_text is an empty string or None.
#   - [edge_case] exception_object_logging: Verify that an Exception object passed as check_error is correctly stringified in the log.
#   - [edge_case] status_code_zero_handling: Verify that a status_code of 0 is logged as 'No response' due to the 'or' logic.

import sys
from unittest.mock import MagicMock

# Mock missing dependencies to allow importing maigret.checking
for mod in ["aiodns", "alive_progress", "python_socks", "socid_extractor", "curl_cffi", "colorama", "xmind", "jinja2", "cloudscraper", "requests"]:
    sys.modules[mod] = MagicMock()

import pytest
import os
from maigret.checking import debug_response_logging

@pytest.mark.generated
@pytest.mark.happy_path
def test_append_multiple_entries(tmp_path, monkeypatch):
    """Verify that multiple calls to debug_response_logging append to the same debug.log file."""
    monkeypatch.chdir(tmp_path)
    debug_response_logging("https://site1.com", None, 200, None)
    debug_response_logging("https://site2.com", None, 404, "Not Found")
    
    log_file = tmp_path / "debug.log"
    assert log_file.exists()
    
    log_content = log_file.read_text()
    assert "https://site1.com" in log_content
    assert "https://site2.com" in log_content
    assert log_content.count("url: ") == 2

@pytest.mark.generated
@pytest.mark.happy_path
def test_html_content_logging(tmp_path, monkeypatch):
    """Verify that html_text is correctly logged with the 'response:' prefix when provided."""
    monkeypatch.chdir(tmp_path)
    debug_response_logging("https://example.com", "<html>test content</html>", 200, None)
    
    log_content = (tmp_path / "debug.log").read_text()
    assert "response: <html>test content</html>" in log_content
    assert "code: 200" in log_content

@pytest.mark.generated
@pytest.mark.edge_case
def test_empty_html_content_omission(tmp_path, monkeypatch):
    """Verify that the 'response:' line is omitted from the log when html_text is an empty string or None."""
    monkeypatch.chdir(tmp_path)
    # Test with empty string
    debug_response_logging("https://example.com", "", 200, None)
    log_content = (tmp_path / "debug.log").read_text()
    assert "response:" not in log_content
    
    # Test with None
    if (tmp_path / "debug.log").exists():
        os.remove(tmp_path / "debug.log")
    debug_response_logging("https://example.com", None, 200, None)
    log_content = (tmp_path / "debug.log").read_text()
    assert "response:" not in log_content

@pytest.mark.generated
@pytest.mark.edge_case
def test_exception_object_logging(tmp_path, monkeypatch):
    """Verify that an Exception object passed as check_error is correctly stringified in the log."""
    monkeypatch.chdir(tmp_path)
    debug_response_logging("https://example.com", None, 200, ValueError("custom error message"))
    
    log_content = (tmp_path / "debug.log").read_text()
    assert "error: custom error message" in log_content

@pytest.mark.generated
@pytest.mark.edge_case
def test_status_code_zero_handling(tmp_path, monkeypatch):
    """Verify that a status_code of 0 is logged as 'No response' due to the 'or' logic."""
    monkeypatch.chdir(tmp_path)
    debug_response_logging("https://example.com", None, 0, None)
    
    log_content = (tmp_path / "debug.log").read_text()
    assert "r: No response" in log_content
