# ROOST_METHOD_HASH=close_39a71cbfe4
# ROOST_METHOD_SIG_HASH=close_ec965e14c1

"""Tests for `maigret.checking.CurlCffiChecker.close`.

Auto-generated by roost-pytest. Re-generate when the source
changes; see the run report for generation details.
"""
# Source: maigret/checking.py:244-245
# Scenarios:
#   - [happy_path] test_close_fresh_instance: Verify that close() can be called and awaited on a freshly initialized CurlCffiChecker instance without errors.
#   - [edge_case] test_close_idempotency: Verify that calling close() multiple times on the same instance is safe and does not raise any exceptions.
#   - [happy_path] test_close_after_prepare: Verify that close() can be called after a prepare() operation has been performed, simulating real-world usage.
#   - [happy_path] test_close_is_async_function: Verify that the close method is an asynchronous function (returns a coroutine).

import sys
from unittest.mock import MagicMock

# Mock missing dependencies to allow importing maigret.checking
mock_modules = [
    'aiodns',
    'alive_progress',
    'socid_extractor',
    'curl_cffi',
    'curl_cffi.requests',
    'aiohttp_socks',
    'python_socks',
    'python_socks._errors',
    'colorama',
    'xmind',
    'jinja2',
    'pandas',
    'openpyxl',
    'cloudscraper',
]
for module_name in mock_modules:
    try:
        __import__(module_name)
    except ImportError:
        sys.modules[module_name] = MagicMock()

import pytest
import inspect
import asyncio
from unittest.mock import Mock
from maigret.checking import CurlCffiChecker

@pytest.mark.generated
@pytest.mark.happy_path
def test_close_fresh_instance():
    """
    Verify that close() can be called and awaited on a freshly initialized CurlCffiChecker instance without errors.
    """
    checker = CurlCffiChecker()
    async def _t():
        await checker.close()
    asyncio.run(_t())

@pytest.mark.generated
@pytest.mark.edge_case
def test_close_idempotency():
    """
    Verify that calling close() multiple times on the same instance is safe and does not raise any exceptions.
    """
    checker = CurlCffiChecker()
    async def _t():
        await checker.close()
        await checker.close()
    asyncio.run(_t())

@pytest.mark.generated
@pytest.mark.happy_path
def test_close_after_prepare():
    """
    Verify that close() can be called after a prepare() operation has been performed, simulating real-world usage.
    """
    checker = CurlCffiChecker(logger=Mock())
    checker.prepare(url='https://example.com')
    async def _t():
        await checker.close()
    asyncio.run(_t())

@pytest.mark.generated
@pytest.mark.nice_to_have
def test_close_is_async_function():
    """
    Verify that the close method is an asynchronous function (returns a coroutine).
    """
    checker = CurlCffiChecker()
    assert inspect.iscoroutinefunction(checker.close)
