# ROOST_METHOD_HASH=get_failed_sites_9653b59d5a
# ROOST_METHOD_SIG_HASH=get_failed_sites_5a2e0ace9c

# NB: existing tests detected for this symbol.
#
# Hand-written test(s) found (no ROOST_METHOD_HASH header):
#   - tests/test_checking.py
# This file was generated ALONGSIDE those — the user's
# tests are kept untouched. The scenarios here may
# differ from what the hand-written file covers.

"""Tests for `maigret.checking.get_failed_sites`.

Auto-generated by roost-pytest. Re-generate when the source
changes; see the run report for generation details.
"""
# Source: maigret/checking.py:735-743
# Scenarios:
#   - [happy_path] multiple_temporary_errors: Verify that multiple sites with different types of temporary errors are all included in the failed sites list.
#   - [happy_path] all_permanent_errors: Verify that sites with permanent errors (Captcha, Access denied) are correctly filtered out.
#   - [edge_case] empty_input: Verify that an empty results dictionary returns an empty list.
#   - [edge_case] no_errors_present: Verify that successful checks and checks with no error object are excluded.
#   - [edge_case] missing_or_empty_status: Verify that results with missing or empty status information are safely ignored and do not cause errors.

import sys
from unittest.mock import MagicMock

# Mock missing dependencies before importing maigret modules
sys.modules['aiodns'] = MagicMock()
sys.modules['alive_progress'] = MagicMock()
sys.modules['socid_extractor'] = MagicMock()
sys.modules['python_socks'] = MagicMock()
sys.modules['colorama'] = MagicMock()
sys.modules['xmind'] = MagicMock()
sys.modules['jinja2'] = MagicMock()
sys.modules['cloudscraper'] = MagicMock()

import pytest
from maigret.checking import get_failed_sites
from maigret.result import MaigretCheckResult, MaigretCheckStatus
from maigret.errors import CheckError

@pytest.mark.generated
@pytest.mark.happy_path
def test_multiple_temporary_errors():
    """Verify that multiple sites with different types of temporary errors are all included in the failed sites list."""
    results = {
        "site1": {"status": MaigretCheckResult("u", "s1", "url", MaigretCheckStatus.UNKNOWN, error=CheckError("Connecting failure"))},
        "site2": {"status": MaigretCheckResult("u", "s2", "url", MaigretCheckStatus.UNKNOWN, error=CheckError("Connection lost"))},
        "site3": {"status": MaigretCheckResult("u", "s3", "url", MaigretCheckStatus.UNKNOWN, error=CheckError("Proxy"))}
    }
    result = get_failed_sites(results)
    assert result == ["site1", "site2", "site3"]

@pytest.mark.generated
@pytest.mark.happy_path
def test_all_permanent_errors():
    """Verify that sites with permanent errors (Captcha, Access denied) are correctly filtered out."""
    results = {
        "site1": {"status": MaigretCheckResult("u", "s1", "url", MaigretCheckStatus.UNKNOWN, error=CheckError("Captcha"))},
        "site2": {"status": MaigretCheckResult("u", "s2", "url", MaigretCheckStatus.UNKNOWN, error=CheckError("Access denied"))}
    }
    result = get_failed_sites(results)
    assert result == []

@pytest.mark.generated
@pytest.mark.edge_case
def test_empty_input():
    """Verify that an empty results dictionary returns an empty list."""
    result = get_failed_sites({})
    assert result == []

@pytest.mark.generated
@pytest.mark.edge_case
def test_no_errors_present():
    """Verify that successful checks and checks with no error object are excluded."""
    results = {
        "site1": {"status": MaigretCheckResult("u", "s1", "url", MaigretCheckStatus.CLAIMED)},
        "site2": {"status": MaigretCheckResult("u", "s2", "url", MaigretCheckStatus.UNKNOWN, error=None)}
    }
    result = get_failed_sites(results)
    assert result == []

@pytest.mark.generated
@pytest.mark.edge_case
def test_missing_or_empty_status():
    """Verify that results with missing or empty status information are safely ignored and do not cause errors."""
    results = {"site1": {}, "site2": {"status": {}}}
    result = get_failed_sites(results)
    assert result == []
