# ROOST_METHOD_HASH=check_368ba0cc7f
# ROOST_METHOD_SIG_HASH=check_7cf19bb4aa

"""Tests for `maigret.checking.AiodnsDomainResolver.check`.

Auto-generated by roost-pytest. Re-generate when the source
changes; see the run report for generation details.
"""
# Source: maigret/checking.py:196-211
# Scenarios:
#   - [happy_path] success_resolution: Verify that a successful DNS resolution returns the host IP and status 200.
#   - [error_path] dns_error: Verify that a DNSError results in a 404 status without a CheckError object.
#   - [error_path] generic_exception: Verify that an unexpected exception is caught, logged, and returns a CheckError.
#   - [edge_case] empty_response: Verify that an empty result list from the resolver is handled as an error (IndexError).

import sys
from unittest.mock import MagicMock

class DNSError(Exception):
    pass

# Mock missing dependencies before importing SUT
def setup_mocks():
    modules_to_mock = {
        'aiodns': ['error'],
        'alive_progress': [],
        'aiohttp': ['client_exceptions'],
        'python_socks': [],
        'socid_extractor': [],
        'colorama': [],
        'xmind': [],
        'maigret.maigret': [],
        'maigret.report': [],
        'maigret.notify': [],
    }
    
    for name, subs in modules_to_mock.items():
        if name not in sys.modules:
            m = MagicMock()
            sys.modules[name] = m
            for sub in subs:
                sm = MagicMock()
                setattr(m, sub, sm)
                sys.modules[f"{name}.{sub}"] = sm
    
    # Special handling for aiodns.error.DNSError
    import aiodns
    aiodns.error.DNSError = DNSError
    if 'aiodns.error' in sys.modules:
        sys.modules['aiodns.error'].DNSError = DNSError

setup_mocks()

import pytest
import asyncio
import aiodns
from unittest.mock import Mock, AsyncMock
from maigret.checking import AiodnsDomainResolver
from maigret.errors import CheckError

@pytest.mark.generated
@pytest.mark.happy_path
def test_success_resolution():
    """Verify that a successful DNS resolution returns the host IP and status 200."""
    async def _t():
        resolver = AiodnsDomainResolver()
        resolver.prepare('google.com')
        mock_res = Mock()
        mock_res.host = '1.2.3.4'
        resolver.resolver.query = AsyncMock(return_value=[mock_res])
        
        result = await resolver.check()
        
        assert result == ('1.2.3.4', 200, None)
        resolver.resolver.query.assert_called_once_with('google.com', 'A')

    asyncio.run(_t())

@pytest.mark.generated
@pytest.mark.error_path
def test_dns_error():
    """Verify that a DNSError results in a 404 status without a CheckError object."""
    async def _t():
        resolver = AiodnsDomainResolver()
        resolver.prepare('nonexistent.test')
        resolver.resolver.query = AsyncMock(side_effect=aiodns.error.DNSError)
        
        result = await resolver.check()
        
        assert result == ('', 404, None)

    asyncio.run(_t())

@pytest.mark.generated
@pytest.mark.error_path
def test_generic_exception():
    """Verify that an unexpected exception is caught, logged, and returns a CheckError."""
    async def _t():
        resolver = AiodnsDomainResolver()
        resolver.prepare('error.test')
        resolver.resolver.query = AsyncMock(side_effect=Exception('Unexpected error'))
        
        result = await resolver.check()
        
        assert result[0] == ''
        assert result[1] == 404
        assert isinstance(result[2], CheckError)
        assert 'Unexpected error' in str(result[2])

    asyncio.run(_t())

@pytest.mark.generated
@pytest.mark.edge_case
def test_empty_response():
    """Verify that an empty result list from the resolver is handled as an error (IndexError)."""
    async def _t():
        resolver = AiodnsDomainResolver()
        resolver.prepare('empty.test')
        resolver.resolver.query = AsyncMock(return_value=[])
        
        result = await resolver.check()
        
        assert result[0] == ''
        assert result[1] == 404
        assert isinstance(result[2], CheckError)
        assert 'list index out of range' in str(result[2])

    asyncio.run(_t())
