# ROOST_METHOD_HASH=self_check_75070721dc
# ROOST_METHOD_SIG_HASH=self_check_48c99f37ef

"""Tests for `maigret.checking.self_check`.

Auto-generated by roost-pytest. Re-generate when the source
changes; see the run report for generation details.
"""
# Source: maigret/checking.py:1121-1220
# Scenarios:
#   - [happy_path] test_self_check_success: Verify that self_check returns success and no update needed when all sites pass.
#   - [edge_case] test_self_check_with_issues_auto_disable_on: Verify that self_check reports update needed when a site is disabled during check.
#   - [happy_path] test_self_check_with_issues_auto_disable_off: Verify that self_check reports issues but no update needed when auto_disable is False.
#   - [happy_path] test_self_check_unchecked_tag_removed: Verify that self_check reports update needed when an 'unchecked' tag is removed from a site.
#   - [error_path] test_self_check_exception_handling: Verify that self_check handles unexpected exceptions in site check tasks gracefully.
#   - [edge_case] test_self_check_empty_sites: Verify that self_check handles empty site data correctly.

import sys
from unittest.mock import MagicMock, Mock, patch, AsyncMock

# Mock missing dependencies before importing maigret.checking
sys.modules["aiodns"] = MagicMock()
sys.modules["alive_progress"] = MagicMock()
sys.modules["socid_extractor"] = MagicMock()
sys.modules["python_socks"] = MagicMock()
sys.modules["curl_cffi"] = MagicMock()
sys.modules["curl_cffi.requests"] = MagicMock()
sys.modules["xmind"] = MagicMock()
sys.modules["jinja2"] = MagicMock()
sys.modules["lxml"] = MagicMock()
sys.modules["lxml.etree"] = MagicMock()
sys.modules["requests_futures"] = MagicMock()
sys.modules["requests_futures.sessions"] = MagicMock()
sys.modules["cloudscraper"] = MagicMock()
sys.modules["requests"] = MagicMock()

colorama_mock = MagicMock()
colorama_mock.Fore = MagicMock()
colorama_mock.Style = MagicMock()
sys.modules["colorama"] = colorama_mock

import pytest
import asyncio
from maigret.checking import self_check

@pytest.mark.generated
@pytest.mark.happy_path
def test_self_check_success():
    """Verify that self_check returns success and no update needed when all sites pass."""
    async def _t():
        site1 = Mock(tags=[], disabled=False)
        site1.name = "site1"
        site2 = Mock(tags=[], disabled=False)
        site2.name = "site2"
        
        # site_self_check is an async function, so we use AsyncMock
        with patch("maigret.checking.site_self_check", new_callable=AsyncMock) as mock_check:
            mock_check.return_value = {"disabled": False, "issues": [], "recommendations": []}
            
            result = await self_check(
                Mock(), 
                {"site1": site1, "site2": site2}, 
                Mock(), 
                silent=True, 
                no_progressbar=True
            )
            
            assert result["needs_update"] is False
            assert result["total_issues"] == 0
            assert len(result["results"]) == 2
            
    asyncio.run(_t())

@pytest.mark.generated
@pytest.mark.edge_case
def test_self_check_with_issues_auto_disable_on():
    """Verify that self_check reports update needed when a site is disabled during check."""
    async def _t():
        site1 = Mock(tags=[], disabled=False)
        site1.name = "site1"
        
        async def side_effect(*args, **kwargs):
            site1.disabled = True
            return {"disabled": True, "issues": ["error"], "recommendations": []}
            
        with patch("maigret.checking.site_self_check", side_effect=side_effect):
            result = await self_check(
                Mock(), 
                {"site1": site1}, 
                Mock(), 
                auto_disable=True, 
                silent=True, 
                no_progressbar=True
            )
            
            assert result["needs_update"] is True
            assert result["total_issues"] == 1
            assert site1.disabled is True
            
    asyncio.run(_t())

@pytest.mark.generated
@pytest.mark.happy_path
def test_self_check_with_issues_auto_disable_off():
    """Verify that self_check reports issues but no update needed when auto_disable is False."""
    async def _t():
        site1 = Mock(tags=[], disabled=False)
        site1.name = "site1"
        
        with patch("maigret.checking.site_self_check", new_callable=AsyncMock) as mock_check:
            mock_check.return_value = {"disabled": True, "issues": ["error"], "recommendations": []}
            
            result = await self_check(
                Mock(), 
                {"site1": site1}, 
                Mock(), 
                auto_disable=False, 
                silent=True, 
                no_progressbar=True
            )
            
            assert result["needs_update"] is False
            assert result["total_issues"] == 1
            assert site1.disabled is False
            
    asyncio.run(_t())

@pytest.mark.generated
@pytest.mark.happy_path
def test_self_check_unchecked_tag_removed():
    """Verify that self_check reports update needed when an 'unchecked' tag is removed from a site."""
    async def _t():
        site1 = Mock(tags=["unchecked"], disabled=False)
        site1.name = "site1"
        
        async def side_effect(*args, **kwargs):
            site1.tags = []
            return {"disabled": False, "issues": [], "recommendations": []}
            
        with patch("maigret.checking.site_self_check", side_effect=side_effect):
            result = await self_check(
                Mock(), 
                {"site1": site1}, 
                Mock(), 
                silent=True, 
                no_progressbar=True
            )
            
            assert result["needs_update"] is True
            assert "unchecked" not in site1.tags
            
    asyncio.run(_t())

@pytest.mark.generated
@pytest.mark.error_path
def test_self_check_exception_handling():
    """Verify that self_check handles unexpected exceptions in site check tasks gracefully."""
    async def _t():
        site1 = Mock(tags=[], disabled=False)
        site1.name = "site1"
        
        # Patching site_self_check to raise an exception when called
        with patch("maigret.checking.site_self_check", side_effect=RuntimeError("Failure")):
            result = await self_check(
                Mock(), 
                {"site1": site1}, 
                Mock(), 
                silent=True, 
                no_progressbar=True
            )
            
            assert result["total_issues"] == 1
            assert "Unexpected error: Failure" in result["results"][0]["issues"]
            
    asyncio.run(_t())

@pytest.mark.generated
@pytest.mark.edge_case
def test_self_check_empty_sites():
    """Verify that self_check handles empty site data correctly."""
    async def _t():
        result = await self_check(
            Mock(), 
            {}, 
            Mock(), 
            silent=True, 
            no_progressbar=True
        )
        
        assert result["needs_update"] is False
        assert result["results"] == []
        assert result["total_issues"] == 0
        
    asyncio.run(_t())
