# ROOST_METHOD_HASH=CurlCffiChecker_b3d5c86c2b
# ROOST_METHOD_SIG_HASH=CurlCffiChecker_dc2abf071b

"""Tests for `maigret.checking.CurlCffiChecker`.

Auto-generated by roost-pytest. Re-generate when the source
changes; see the run report for generation details.
"""
# Source: maigret/checking.py:222-287
# Scenarios:
#   - [happy_path] prepare_sets_attributes: Verify that the prepare method correctly sets all request parameters on the checker instance.
#   - [happy_path] check_get_success: Verify that a successful GET request returns the expected content and status code.
#   - [happy_path] check_post_with_payload: Verify that a POST request correctly passes the JSON payload to the session.
#   - [edge_case] check_headers_filtering: Verify that User-Agent and Connection headers are stripped to allow curl_cffi to use its own impersonation headers.
#   - [error_path] check_timeout_error: Verify that asyncio.TimeoutError is caught and converted into a CheckError.
#   - [edge_case] check_connection_lost_error: Verify that a status code of 0 is treated as a "Connection lost" error.
#   - [error_path] check_unexpected_exception: Verify that generic exceptions are caught and converted into an "Unexpected" CheckError.

import sys
from unittest.mock import MagicMock

# Mock missing dependencies to allow importing maigret.checking
for module in ['aiodns', 'alive_progress', 'socid_extractor', 'python_socks', 'colorama', 'aiohttp_socks', 'xmind', 'jinja2', 'cloudscraper']:
    if module not in sys.modules:
        sys.modules[module] = MagicMock()

import asyncio
import pytest
from unittest.mock import patch, MagicMock
import maigret.checking
from maigret.checking import CurlCffiChecker
from maigret.errors import CheckError

# Ensure CurlCffiAsyncSession exists in maigret.checking for patching
if not hasattr(maigret.checking, 'CurlCffiAsyncSession'):
    maigret.checking.CurlCffiAsyncSession = MagicMock()

@pytest.mark.generated
@pytest.mark.happy_path
def test_prepare_sets_attributes():
    """Verify that the prepare method correctly sets all request parameters on the checker instance."""
    checker = CurlCffiChecker()
    checker.prepare(
        url="https://example.com",
        headers={"X-Test": "val"},
        method="post",
        payload={"a": 1},
        timeout=5,
        allow_redirects=False
    )
    assert checker.url == "https://example.com"
    assert checker.headers == {"X-Test": "val"}
    assert checker.method == "post"
    assert checker.payload == {"a": 1}
    assert checker.timeout == 5
    assert checker.allow_redirects == False

@pytest.mark.generated
@pytest.mark.happy_path
def test_check_get_success():
    """Verify that a successful GET request returns the expected content and status code."""
    async def _t():
        checker = CurlCffiChecker()
        checker.prepare(url="https://example.com")
        
        with patch("maigret.checking.CurlCffiAsyncSession") as mock_session_cls:
            mock_session = MagicMock()
            mock_session_cls.return_value = mock_session
            
            async def mock_aenter():
                return mock_session
            mock_session.__aenter__.side_effect = mock_aenter
            
            async def mock_aexit(*args):
                pass
            mock_session.__aexit__.side_effect = mock_aexit
            
            mock_response = MagicMock()
            mock_response.status_code = 200
            mock_response.text = "success content"
            
            async def mock_get(**kwargs):
                return mock_response
            mock_session.get.side_effect = mock_get
            
            result = await checker.check()
            
            assert result == ("success content", 200, None)
            mock_session.get.assert_called_once()

    asyncio.run(_t())

@pytest.mark.generated
@pytest.mark.happy_path
def test_check_post_with_payload():
    """Verify that a POST request correctly passes the JSON payload to the session."""
    async def _t():
        checker = CurlCffiChecker()
        checker.prepare(url="https://example.com", method="post", payload={"key": "value"})
        
        with patch("maigret.checking.CurlCffiAsyncSession") as mock_session_cls:
            mock_session = MagicMock()
            mock_session_cls.return_value = mock_session
            
            async def mock_aenter():
                return mock_session
            mock_session.__aenter__.side_effect = mock_aenter
            
            async def mock_aexit(*args):
                pass
            mock_session.__aexit__.side_effect = mock_aexit
            
            mock_response = MagicMock()
            mock_response.status_code = 201
            mock_response.text = "created"
            
            async def mock_post(**kwargs):
                return mock_response
            mock_session.post.side_effect = mock_post
            
            result = await checker.check()
            
            assert result == ("created", 201, None)
            mock_session.post.assert_called_once_with(
                url="https://example.com",
                headers=None,
                allow_redirects=True,
                timeout=10,
                impersonate="chrome",
                json={"key": "value"}
            )

    asyncio.run(_t())

@pytest.mark.generated
@pytest.mark.edge_case
def test_check_headers_filtering():
    """Verify that User-Agent and Connection headers are stripped to allow curl_cffi to use its own impersonation headers."""
    async def _t():
        checker = CurlCffiChecker()
        checker.prepare(
            url="https://example.com",
            headers={"User-Agent": "custom-ua", "Connection": "keep-alive", "X-Custom": "val"}
        )
        
        with patch("maigret.checking.CurlCffiAsyncSession") as mock_session_cls:
            mock_session = MagicMock()
            mock_session_cls.return_value = mock_session
            
            async def mock_aenter():
                return mock_session
            mock_session.__aenter__.side_effect = mock_aenter
            
            async def mock_aexit(*args):
                pass
            mock_session.__aexit__.side_effect = mock_aexit
            
            mock_response = MagicMock()
            mock_response.status_code = 200
            mock_response.text = ""
            
            async def mock_get(**kwargs):
                return mock_response
            mock_session.get.side_effect = mock_get
            
            await checker.check()
            
            sent_headers = mock_session.get.call_args.kwargs["headers"]
            assert sent_headers == {"X-Custom": "val"}
            assert "User-Agent" not in sent_headers
            assert "Connection" not in sent_headers

    asyncio.run(_t())

@pytest.mark.generated
@pytest.mark.error_path
def test_check_timeout_error():
    """Verify that asyncio.TimeoutError is caught and converted into a CheckError."""
    async def _t():
        checker = CurlCffiChecker()
        checker.prepare(url="https://example.com")
        
        with patch("maigret.checking.CurlCffiAsyncSession") as mock_session_cls:
            mock_session = MagicMock()
            mock_session_cls.return_value = mock_session
            
            async def mock_aenter():
                return mock_session
            mock_session.__aenter__.side_effect = mock_aenter
            
            async def mock_aexit(*args):
                pass
            mock_session.__aexit__.side_effect = mock_aexit
            
            async def mock_get(**kwargs):
                raise asyncio.TimeoutError("timeout")
            mock_session.get.side_effect = mock_get
            
            result = await checker.check()
            
            assert result[0] is None
            assert result[1] == 0
            assert isinstance(result[2], CheckError)
            assert result[2].type == "Request timeout"

    asyncio.run(_t())

@pytest.mark.generated
@pytest.mark.edge_case
def test_check_connection_lost_error():
    """Verify that a status code of 0 is treated as a "Connection lost" error."""
    async def _t():
        checker = CurlCffiChecker()
        checker.prepare(url="https://example.com")
        
        with patch("maigret.checking.CurlCffiAsyncSession") as mock_session_cls:
            mock_session = MagicMock()
            mock_session_cls.return_value = mock_session
            
            async def mock_aenter():
                return mock_session
            mock_session.__aenter__.side_effect = mock_aenter
            
            async def mock_aexit(*args):
                pass
            mock_session.__aexit__.side_effect = mock_aexit
            
            mock_response = MagicMock()
            mock_response.status_code = 0
            mock_response.text = ""
            
            async def mock_get(**kwargs):
                return mock_response
            mock_session.get.side_effect = mock_get
            
            result = await checker.check()
            
            assert result[1] == 0
            assert isinstance(result[2], CheckError)
            assert result[2].type == "Connection lost"

    asyncio.run(_t())

@pytest.mark.generated
@pytest.mark.error_path
def test_check_unexpected_exception():
    """Verify that generic exceptions are caught and converted into an "Unexpected" CheckError."""
    async def _t():
        checker = CurlCffiChecker()
        checker.prepare(url="https://example.com")
        
        with patch("maigret.checking.CurlCffiAsyncSession") as mock_session_cls:
            mock_session = MagicMock()
            mock_session_cls.return_value = mock_session
            
            async def mock_aenter():
                return mock_session
            mock_session.__aenter__.side_effect = mock_aenter
            
            async def mock_aexit(*args):
                pass
            mock_session.__aexit__.side_effect = mock_aexit
            
            async def mock_get(**kwargs):
                raise RuntimeError("unexpected boom")
            mock_session.get.side_effect = mock_get
            
            result = await checker.check()
            
            assert result[0] is None
            assert result[1] == 0
            assert isinstance(result[2], CheckError)
            assert result[2].type == "Unexpected"
            assert "unexpected boom" in result[2].desc

    asyncio.run(_t())
