# ROOST_METHOD_HASH=AiodnsDomainResolver.__init___503cf22c62
# ROOST_METHOD_SIG_HASH=AiodnsDomainResolver.__init___dc2abf071b

"""Tests for `maigret.checking.AiodnsDomainResolver.__init__`.

Auto-generated by roost-pytest. Re-generate when the source
changes; see the run report for generation details.
"""
# Source: maigret/checking.py:187-190
# Scenarios:
#   - [happy_path] happy_path_default: Verify that AiodnsDomainResolver initializes correctly with default parameters.
#   - [happy_path] happy_path_with_logger: Verify that AiodnsDomainResolver uses the provided logger.
#   - [edge_case] edge_case_extra_args: Verify that AiodnsDomainResolver handles extra positional and keyword arguments without error.
#   - [error_path] error_path_no_event_loop: Verify behavior when asyncio.get_event_loop() fails.
#   - [error_path] error_path_aiodns_init_failure: Verify that errors during aiodns.DNSResolver initialization are propagated.

import sys
from unittest.mock import Mock

# Mock missing third-party dependencies before importing SUT
for mod in [
    'aiodns', 'alive_progress', 'aiohttp', 'aiohttp.client_exceptions',
    'python_socks', 'socid_extractor', 'colorama', 'requests', 'bs4',
    'lxml', 'future', 'mock', 'cloudscraper', 'selenium', 'fake_useragent',
    'xmind', 'jinja2', 'pycountry', 'networkx', 'matplotlib', 'pandas',
    'openpyxl', 'tabulate'
]:
    sys.modules[mod] = Mock()

import pytest
from unittest.mock import patch
from maigret.checking import AiodnsDomainResolver

@pytest.mark.generated
@pytest.mark.happy_path
def test_happy_path_default():
    """Verify that AiodnsDomainResolver initializes correctly with default parameters."""
    with patch('maigret.checking.asyncio.get_event_loop') as mock_get_loop, \
         patch('maigret.checking.aiodns.DNSResolver') as mock_dns_resolver:
        mock_loop = Mock()
        mock_get_loop.return_value = mock_loop
        
        resolver = AiodnsDomainResolver()
        
        # The SUT uses Mock() as default logger if not provided.
        # We check if it's a Mock instance.
        assert isinstance(resolver.logger, Mock)
        assert resolver.resolver == mock_dns_resolver.return_value
        mock_dns_resolver.assert_called_once_with(loop=mock_loop)

@pytest.mark.generated
@pytest.mark.happy_path
def test_happy_path_with_logger():
    """Verify that AiodnsDomainResolver uses the provided logger."""
    mock_logger = Mock()
    with patch('maigret.checking.asyncio.get_event_loop'), \
         patch('maigret.checking.aiodns.DNSResolver'):
        resolver = AiodnsDomainResolver(logger=mock_logger)
        assert resolver.logger == mock_logger

@pytest.mark.generated
@pytest.mark.edge_case
def test_edge_case_extra_args():
    """Verify that AiodnsDomainResolver handles extra positional and keyword arguments without error."""
    with patch('maigret.checking.asyncio.get_event_loop'), \
         patch('maigret.checking.aiodns.DNSResolver'):
        # The __init__ signature is (self, *args, **kwargs)
        resolver = AiodnsDomainResolver("extra_pos_arg", custom_kwarg="value")
        assert isinstance(resolver.logger, Mock)
        assert resolver.resolver is not None

@pytest.mark.generated
@pytest.mark.error_path
def test_error_path_no_event_loop():
    """Verify behavior when asyncio.get_event_loop() fails."""
    with patch('maigret.checking.asyncio.get_event_loop', side_effect=RuntimeError("no running event loop")):
        with pytest.raises(RuntimeError, match="no running event loop"):
            AiodnsDomainResolver()

@pytest.mark.generated
@pytest.mark.error_path
def test_error_path_aiodns_init_failure():
    """Verify that errors during aiodns.DNSResolver initialization are propagated."""
    with patch('maigret.checking.asyncio.get_event_loop'), \
         patch('maigret.checking.aiodns.DNSResolver', side_effect=Exception("DNS init failed")):
        with pytest.raises(Exception, match="DNS init failed"):
            AiodnsDomainResolver()
