# ROOST_METHOD_HASH=SUPPORTED_IDS_866888e8af
# ROOST_METHOD_SIG_HASH=SUPPORTED_IDS_866888e8af

"""Tests for `maigret.checking.SUPPORTED_IDS`.

Auto-generated by roost-pytest. Re-generate when the source
changes; see the run report for generation details.
"""
# Source: maigret/checking.py:36-46
# Scenarios:
#   - [happy_path] test_supported_ids_type_and_elements: Verify that SUPPORTED_IDS is a tuple containing only string elements.
#   - [regression] test_supported_ids_content_regression: Verify that SUPPORTED_IDS contains the expected set of supported ID types for regression.
#   - [edge_case] test_supported_ids_no_duplicates: Verify that there are no duplicate entries in the SUPPORTED_IDS tuple.
#   - [happy_path] test_parse_usernames_all_supported_ids: Verify that parse_usernames correctly processes a dictionary where all keys are in SUPPORTED_IDS.
#   - [error_path] test_parse_usernames_ignores_unsupported_ids: Verify that parse_usernames ignores keys that are not in SUPPORTED_IDS and don't match the username pattern.

import sys
from unittest.mock import Mock

# Mock missing dependencies before importing maigret.checking
# This is necessary because the environment might lack some third-party dependencies
# that are imported at the module level in maigret.checking or its dependencies.
for mod in [
    'aiodns', 'alive_progress', 'socid_extractor', 'python_socks',
    'colorama', 'xmind', 'jinja2', 'dateutil', 'dateutil.tz', 'dateutil.parser',
    'cloudscraper'
]:
    sys.modules[mod] = Mock()

import pytest
from maigret.checking import SUPPORTED_IDS, parse_usernames

@pytest.mark.generated
@pytest.mark.happy_path
def test_supported_ids_type_and_elements():
    """Verify that SUPPORTED_IDS is a tuple containing only string elements."""
    assert isinstance(SUPPORTED_IDS, tuple)
    assert all(isinstance(i, str) for i in SUPPORTED_IDS)

@pytest.mark.generated
@pytest.mark.regression
def test_supported_ids_content_regression():
    """Verify that SUPPORTED_IDS contains the expected set of supported ID types for regression."""
    expected = {
        'username', 'yandex_public_id', 'gaia_id', 'vk_id', 'ok_id',
        'wikimapia_uid', 'steam_id', 'uidme_uguid', 'yelp_userid'
    }
    assert set(SUPPORTED_IDS) == expected

@pytest.mark.generated
@pytest.mark.edge_case
def test_supported_ids_no_duplicates():
    """Verify that there are no duplicate entries in the SUPPORTED_IDS tuple."""
    assert len(SUPPORTED_IDS) == len(set(SUPPORTED_IDS))

@pytest.mark.generated
@pytest.mark.happy_path
def test_parse_usernames_all_supported_ids():
    """Verify that parse_usernames correctly processes a dictionary where all keys are in SUPPORTED_IDS."""
    data = {k: f'val_{k}' for k in SUPPORTED_IDS}
    result = parse_usernames(data, Mock())
    assert all(result.get(f'val_{k}') == k for k in SUPPORTED_IDS)

@pytest.mark.generated
@pytest.mark.error_path
def test_parse_usernames_ignores_unsupported_ids():
    """Verify that parse_usernames ignores keys that are not in SUPPORTED_IDS and don't match the username pattern."""
    data = {'unsupported_key': 'some_val', 'another_one': 'val2'}
    result = parse_usernames(data, Mock())
    assert result == {}
