# ROOST_METHOD_HASH=CheckerMock_8b9a501d06
# ROOST_METHOD_SIG_HASH=CheckerMock_dc2abf071b

"""Tests for `maigret.checking.CheckerMock`.

Auto-generated by roost-pytest. Re-generate when the source
changes; see the run report for generation details.
"""
# Source: maigret/checking.py:290-302
# Scenarios:
#   - [happy_path] test_init_with_arbitrary_args: Verify that CheckerMock can be initialized with any positional and keyword arguments.
#   - [happy_path] test_prepare_returns_none: Verify that the prepare method accepts standard checker arguments and returns None.
#   - [happy_path] test_check_returns_default_values: Verify that the async check method returns the default empty result tuple.
#   - [happy_path] test_close_completes_successfully: Verify that the async close method can be called and returns None.
#   - [edge_case] test_check_return_type_signature: Verify that the return value of check() matches the expected type signature.

import sys
from unittest.mock import MagicMock

# Mock missing dependencies before importing maigret.checking
for mod in [
    'aiodns', 'alive_progress', 'socid_extractor', 'python_socks',
    'aiohttp', 'aiohttp.client_exceptions', 'colorama', 'xmind',
    'jinja2', 'dateutil', 'dateutil.tz', 'dateutil.parser',
    'cloudscraper', 'requests', 'yaml', 'tqdm'
]:
    sys.modules[mod] = MagicMock()

import pytest
import asyncio
from maigret.checking import CheckerMock

@pytest.mark.generated
@pytest.mark.happy_path
def test_init_with_arbitrary_args():
    """Verify that CheckerMock can be initialized with any positional and keyword arguments."""
    CheckerMock(1, "test", key="value")

@pytest.mark.generated
@pytest.mark.happy_path
def test_prepare_returns_none():
    """Verify that the prepare method accepts standard checker arguments and returns None."""
    checker = CheckerMock()
    result = checker.prepare("http://example.com", headers={"User-Agent": "test"}, timeout=5, method="POST", payload={"data": 1})
    assert result is None

@pytest.mark.generated
@pytest.mark.happy_path
def test_check_returns_default_values():
    """Verify that the async check method returns the default empty result tuple."""
    checker = CheckerMock()
    
    async def _t():
        return await checker.check()
    
    result = asyncio.run(_t())
    assert result == ('', 0, None)

@pytest.mark.generated
@pytest.mark.happy_path
def test_close_completes_successfully():
    """Verify that the async close method can be called and returns None."""
    checker = CheckerMock()
    
    async def _t():
        return await checker.close()
    
    result = asyncio.run(_t())
    assert result is None

@pytest.mark.generated
@pytest.mark.edge_case
def test_check_return_type_signature():
    """Verify that the return value of check() matches the expected type signature."""
    checker = CheckerMock()
    
    async def _t():
        return await checker.check()
    
    result = asyncio.run(_t())
    assert isinstance(result, tuple)
    assert len(result) == 3
    assert isinstance(result[0], str)
    assert isinstance(result[1], int)
    assert result[2] is None
