# ROOST_METHOD_HASH=CheckerBase_e63152b945
# ROOST_METHOD_SIG_HASH=CheckerBase_e63152b945

"""Tests for `maigret.checking.CheckerBase`.

Auto-generated by roost-pytest. Re-generate when the source
changes; see the run report for generation details.
"""
# Source: maigret/checking.py:51-52
# Scenarios:
#   - [happy_path] test_checker_base_instantiation: Verify that the CheckerBase class can be instantiated directly.
#   - [happy_path] test_checker_base_subclassing: Verify that a custom class inheriting from CheckerBase is recognized as an instance of CheckerBase.
#   - [happy_path] test_existing_checkers_inheritance: Verify that all primary checker implementations in the module inherit from CheckerBase.

import sys
from unittest.mock import MagicMock

# Mock missing dependencies to allow importing maigret.checking
# We mock them in sys.modules before importing the SUT
mock_modules = [
    'aiodns',
    'alive_progress',
    'aiohttp',
    'aiohttp.client_exceptions',
    'python_socks',
    'socid_extractor',
    'aiohttp_socks',
    'curl_cffi',
    'curl_cffi.requests',
    'colorama',
    'future',
    'requests',
    'requests_futures',
    'torrequest',
    'cloudscraper',
    'bs4',
    'lxml',
    'yaml',
    'xmind',
    'jinja2',
    'pandas',
    'openpyxl',
    'odf',
]

for mod in mock_modules:
    if mod not in sys.modules:
        sys.modules[mod] = MagicMock()

import pytest
from maigret.checking import CheckerBase, SimpleAiohttpChecker, CurlCffiChecker, AiodnsDomainResolver

@pytest.mark.generated
@pytest.mark.happy_path
def test_checker_base_instantiation():
    """Verify that the CheckerBase class can be instantiated directly."""
    # arrange: from maigret.checking import CheckerBase
    # act: CheckerBase()
    # assert: The instantiation should succeed without raising any exceptions.
    checker = CheckerBase()
    assert isinstance(checker, CheckerBase)

@pytest.mark.generated
@pytest.mark.happy_path
def test_checker_base_subclassing():
    """Verify that a custom class inheriting from CheckerBase is recognized as an instance of CheckerBase."""
    # arrange: from maigret.checking import CheckerBase; class MyChecker(CheckerBase): pass
    class MyChecker(CheckerBase):
        pass
    
    # act: isinstance(MyChecker(), CheckerBase)
    # assert: The result should be True.
    assert isinstance(MyChecker(), CheckerBase)

@pytest.mark.generated
@pytest.mark.happy_path
def test_existing_checkers_inheritance():
    """Verify that all primary checker implementations in the module inherit from CheckerBase."""
    # arrange: from maigret.checking import CheckerBase, SimpleAiohttpChecker, CurlCffiChecker, AiodnsDomainResolver
    checkers = [SimpleAiohttpChecker, CurlCffiChecker, AiodnsDomainResolver]
    
    # act: [issubclass(c, CheckerBase) for c in [SimpleAiohttpChecker, CurlCffiChecker, AiodnsDomainResolver]]
    results = [issubclass(c, CheckerBase) for c in checkers]
    
    # assert: All elements in the resulting list should be True.
    assert all(results), f"Not all checkers inherit from CheckerBase: {list(zip(checkers, results))}"
