# ROOST_METHOD_HASH=CheckerMock.__init___89091838e2
# ROOST_METHOD_SIG_HASH=CheckerMock.__init___dc2abf071b

"""Tests for `maigret.checking.CheckerMock.__init__`.

Auto-generated by roost-pytest. Re-generate when the source
changes; see the run report for generation details.
"""
# Source: maigret/checking.py:291-292
# Scenarios:
#   - [happy_path] init_no_args: Verify that CheckerMock can be instantiated without any arguments, as it is currently used in the codebase.
#   - [edge_case] init_with_keyword_args: Verify that CheckerMock can be instantiated with keyword arguments, ensuring it can act as a drop-in replacement for other checkers that take such arguments.
#   - [edge_case] init_with_positional_args: Verify that CheckerMock can be instantiated with positional arguments, ensuring its *args signature is functional.

import sys
from unittest.mock import MagicMock

# Mock all potentially missing external dependencies
external_mocks = [
    'aiodns', 'alive_progress', 'socid_extractor', 'python_socks', 
    'python_socks._errors', 'aiohttp', 'aiohttp.client_exceptions', 
    'curl_cffi', 'curl_cffi.requests', 'colorama', 'xmind', 'jinja2', 
    'requests', 'future', 'torrequest', 'cloudscraper', 'bs4', 'lxml'
]
for m in external_mocks:
    if m not in sys.modules:
        sys.modules[m] = MagicMock()

# Mock other submodules of maigret to avoid their dependencies during maigret/__init__ execution
# We don't mock __version__ as it's simple and needed by __init__.py
sys.modules['maigret.maigret'] = MagicMock()
sys.modules['maigret.sites'] = MagicMock()
sys.modules['maigret.notify'] = MagicMock()

import pytest
# Now we can safely import CheckerMock
from maigret.checking import CheckerMock

@pytest.mark.generated
@pytest.mark.happy_path
def test_init_no_args():
    """Verify that CheckerMock can be instantiated without any arguments, as it is currently used in the codebase."""
    checker = CheckerMock()
    assert isinstance(checker, CheckerMock)

@pytest.mark.generated
@pytest.mark.edge_case
def test_init_with_keyword_args():
    """Verify that CheckerMock can be instantiated with keyword arguments, ensuring it can act as a drop-in replacement for other checkers that take such arguments."""
    checker = CheckerMock(proxy="http://127.0.0.1:8080", logger=None)
    assert isinstance(checker, CheckerMock)

@pytest.mark.generated
@pytest.mark.edge_case
def test_init_with_positional_args():
    """Verify that CheckerMock can be instantiated with positional arguments, ensuring its *args signature is functional."""
    checker = CheckerMock("positional_arg", 123)
    assert isinstance(checker, CheckerMock)
