# ROOST_METHOD_HASH=check_site_for_username_6a57cb50ff
# ROOST_METHOD_SIG_HASH=check_site_for_username_328904d4fc

"""Tests for `maigret.checking.check_site_for_username`.

Auto-generated by roost-pytest. Re-generate when the source
changes; see the run report for generation details.
"""
# Source: maigret/checking.py:667-723
# Scenarios:
#   - [happy_path] happy_path_claimed: Verify that a successful status code check returns CLAIMED.
#   - [happy_path] happy_path_available: Verify that a 404 status code check returns AVAILABLE.
#   - [edge_case] activation_retry_success: Verify that the function retries the check if an activation mark is found in the response.
#   - [error_path] checker_error_handling: Verify that a checker error results in an UNKNOWN status.
#   - [error_path] missing_checker_error: Verify behavior when no checker is available for the site's protocol.

import sys
from unittest.mock import MagicMock, Mock, AsyncMock, patch

# Mock missing dependencies before they are imported by maigret
for mod in [
    "aiodns", "alive_progress", "socid_extractor", "python_socks", 
    "curl_cffi", "curl_cffi.requests", "colorama", "aiohttp_socks", 
    "xmind", "jinja2", "cloudscraper", "requests_futures", 
    "requests_futures.sessions", "future", "future.utils"
]:
    sys.modules[mod] = MagicMock()

import pytest
import asyncio
from maigret.checking import check_site_for_username
from maigret.sites import MaigretSite
from maigret.result import MaigretCheckStatus
from maigret.errors import CheckError

@pytest.mark.generated
@pytest.mark.happy_path
def test_happy_path_claimed():
    """Verify that a successful status code check returns CLAIMED."""
    async def _t():
        site = MaigretSite("TestSite", {"url": "https://site.com/{username}", "checkType": "status_code"})
        checker = Mock()
        checker.check = AsyncMock(return_value=("", 200, None))
        checker.prepare = Mock(return_value=None)
        
        options = {
            "parsing": False, 
            "checkers": {"": checker}, 
            "timeout": 10, 
            "id_type": "username",
            "forced": False
        }
        logger = Mock()
        query_notify = Mock()
        
        _, result = await check_site_for_username(site, "testuser", options, logger, query_notify)
        assert result["status"].status == MaigretCheckStatus.CLAIMED

    asyncio.run(_t())

@pytest.mark.generated
@pytest.mark.happy_path
def test_happy_path_available():
    """Verify that a 404 status code check returns AVAILABLE."""
    async def _t():
        site = MaigretSite("TestSite", {"url": "https://site.com/{username}", "checkType": "status_code"})
        checker = Mock()
        checker.check = AsyncMock(return_value=("", 404, None))
        checker.prepare = Mock(return_value=None)
        
        options = {
            "parsing": False, 
            "checkers": {"": checker}, 
            "timeout": 10, 
            "id_type": "username",
            "forced": False
        }
        logger = Mock()
        query_notify = Mock()
        
        _, result = await check_site_for_username(site, "testuser", options, logger, query_notify)
        assert result["status"].status == MaigretCheckStatus.AVAILABLE

    asyncio.run(_t())

@pytest.mark.generated
@pytest.mark.edge_case
def test_activation_retry_success():
    """Verify that the function retries the check if an activation mark is found in the response."""
    async def _t():
        site = MaigretSite("TestSite", {
            "url": "https://site.com/{username}", 
            "checkType": "status_code", 
            "activation": {"marks": ["retry"], "method": "twitter"}
        })
        checker = Mock()
        checker.check = AsyncMock()
        # First call returns "retry", second returns "success"
        checker.check.side_effect = [("retry", 200, None), ("success", 200, None)]
        checker.prepare = Mock(return_value=None)
        checker.url = "https://site.com/testuser"
        checker.headers = {}
        checker.allow_redirects = True
        checker.timeout = 10
        checker.method = "get"
        checker.payload = None
        
        options = {
            "parsing": False, 
            "checkers": {"": checker}, 
            "timeout": 10, 
            "id_type": "username",
            "forced": False
        }
        logger = Mock()
        query_notify = Mock()
        
        with patch("maigret.checking.ParsingActivator") as MockActivator:
            mock_activator_instance = MockActivator.return_value
            mock_activator_instance.twitter = Mock()
            
            _, result = await check_site_for_username(site, "testuser", options, logger, query_notify)
            
            assert checker.check.await_count == 2
            assert result["status"].status == MaigretCheckStatus.CLAIMED
            mock_activator_instance.twitter.assert_called_once()

    asyncio.run(_t())

@pytest.mark.generated
@pytest.mark.error_path
def test_checker_error_handling():
    """Verify that a checker error results in an UNKNOWN status."""
    async def _t():
        site = MaigretSite("TestSite", {"url": "https://site.com/{username}", "checkType": "status_code"})
        checker = Mock()
        checker.check = AsyncMock(return_value=(None, 0, CheckError("Connection failed")))
        checker.prepare = Mock(return_value=None)
        
        options = {
            "parsing": False, 
            "checkers": {"": checker}, 
            "timeout": 10, 
            "id_type": "username",
            "forced": False
        }
        logger = Mock()
        query_notify = Mock()
        
        _, result = await check_site_for_username(site, "testuser", options, logger, query_notify)
        assert result["status"].status == MaigretCheckStatus.UNKNOWN
        assert "Connection failed" in str(result["status"].error)

    asyncio.run(_t())

@pytest.mark.generated
@pytest.mark.error_path
@pytest.mark.xfail(reason="make_site_result raises KeyError when checker is missing instead of returning ILLEGAL status")
def test_missing_checker_error():
    """Verify behavior when no checker is available for the site's protocol."""
    # NB: Source-code gap. maigret/checking.py:615 directly accesses options["checkers"][site.protocol]
    # without checking if the key exists. If it's missing, it raises KeyError.
    # The scenario expects MaigretCheckStatus.ILLEGAL.
    async def _t():
        site = MaigretSite("TestSite", {"url": "https://site.com/{username}", "checkType": "status_code"})
        options = {
            "parsing": False, 
            "checkers": {}, 
            "timeout": 10, 
            "id_type": "username",
            "forced": False
        }
        logger = Mock()
        query_notify = Mock()
        
        _, result = await check_site_for_username(site, "testuser", options, logger, query_notify)
        assert result["status"].status == MaigretCheckStatus.ILLEGAL

    asyncio.run(_t())
