# ROOST_METHOD_HASH=SimpleAiohttpChecker.__init___9e2ea204c2
# ROOST_METHOD_SIG_HASH=SimpleAiohttpChecker.__init___dc2abf071b

"""Tests for `maigret.checking.SimpleAiohttpChecker.__init__`.

Auto-generated by roost-pytest. Re-generate when the source
changes; see the run report for generation details.
"""
# Source: maigret/checking.py:56-65
# Scenarios:
#   - [happy_path] test_init_defaults: Verify that SimpleAiohttpChecker initializes with correct default values when no arguments are provided.
#   - [happy_path] test_init_with_custom_values: Verify that SimpleAiohttpChecker correctly assigns proxy, cookie_jar, and logger when provided as keyword arguments.
#   - [edge_case] test_init_extra_args_ignored: Verify that SimpleAiohttpChecker handles extra positional and keyword arguments without error and ignores them.

import sys
from unittest.mock import MagicMock

# Mock missing dependencies to allow importing maigret.checking
sys.modules['aiodns'] = MagicMock()
sys.modules['alive_progress'] = MagicMock()
sys.modules['python_socks'] = MagicMock()
sys.modules['socid_extractor'] = MagicMock()
sys.modules['aiohttp_socks'] = MagicMock()
sys.modules['colorama'] = MagicMock()
sys.modules['xmind'] = MagicMock()
sys.modules['jinja2'] = MagicMock()
sys.modules['cloudscraper'] = MagicMock()
sys.modules['requests'] = MagicMock()

import pytest
try:
    from mock import Mock
except ImportError:
    from unittest.mock import Mock

from maigret.checking import SimpleAiohttpChecker

@pytest.mark.generated
@pytest.mark.happy_path
def test_init_defaults():
    """Verify that SimpleAiohttpChecker initializes with correct default values when no arguments are provided."""
    checker = SimpleAiohttpChecker()
    assert checker.proxy is None
    assert checker.cookie_jar is None
    assert isinstance(checker.logger, Mock)
    assert checker.url is None
    assert checker.headers is None
    assert checker.allow_redirects is True
    assert checker.timeout == 0
    assert checker.method == 'get'
    assert checker.payload is None

@pytest.mark.generated
@pytest.mark.happy_path
def test_init_with_custom_values():
    """Verify that SimpleAiohttpChecker correctly assigns proxy, cookie_jar, and logger when provided as keyword arguments."""
    mock_cookie_jar = Mock()
    mock_logger = Mock()
    checker = SimpleAiohttpChecker(proxy='http://proxy.com', cookie_jar=mock_cookie_jar, logger=mock_logger)
    assert checker.proxy == 'http://proxy.com'
    assert checker.cookie_jar == mock_cookie_jar
    assert checker.logger == mock_logger

@pytest.mark.generated
@pytest.mark.edge_case
def test_init_extra_args_ignored():
    """Verify that SimpleAiohttpChecker handles extra positional and keyword arguments without error and ignores them."""
    checker = SimpleAiohttpChecker("arg1", extra_param="value")
    assert checker.proxy is None
    assert not hasattr(checker, 'extra_param')
