# ROOST_METHOD_HASH=extract_ids_data_3fb640b74b
# ROOST_METHOD_SIG_HASH=extract_ids_data_885ce11826

# NB: existing tests detected for this symbol.
#
# Hand-written test(s) found (no ROOST_METHOD_HASH header):
#   - tests/test_checking.py
# This file was generated ALONGSIDE those — the user's
# tests are kept untouched. The scenarios here may
# differ from what the hand-written file covers.

"""Tests for `maigret.checking.extract_ids_data`.

Auto-generated by roost-pytest. Re-generate when the source
changes; see the run report for generation details.
"""
# Source: maigret/checking.py:1223-1228
# Scenarios:
#   - [happy_path] happy_path_extraction: Verify that extract_ids_data returns the data provided by the underlying extract function when successful.
#   - [error_path] extraction_exception_handling: Verify that exceptions during extraction are caught, logged with the site name, and an empty dictionary is returned.
#   - [edge_case] empty_html_input: Verify that empty HTML input is handled gracefully (returning whatever the extractor returns, usually an empty dict).
#   - [edge_case] none_html_input: Verify that passing None as html_text (which might cause a TypeError in the extractor) is caught by the exception handler.

import sys
from unittest.mock import Mock

# Mock missing dependencies before importing the SUT
for mod in [
    'aiodns', 'socid_extractor', 'alive_progress', 'python_socks', 
    'colorama', 'xmind', 'jinja2', 'pandas', 'openpyxl', 'odf', 
    'tabulate', 'pycountry', 'cloudscraper', 'fake_useragent'
]:
    sys.modules[mod] = Mock()

import pytest
from unittest.mock import patch
from maigret.checking import extract_ids_data

@pytest.mark.generated
@pytest.mark.happy_path
def test_happy_path_extraction():
    """Verify that extract_ids_data returns the data provided by the underlying extract function when successful."""
    mock_data = {"username": "found_user", "website": "https://site.com/found_user"}
    logger = Mock()
    site = Mock()
    site.name = "TestSite"
    
    with patch('maigret.checking.extract', return_value=mock_data):
        result = extract_ids_data("<html>...</html>", logger, site)
        
    assert result == mock_data
    assert logger.warning.called is False

@pytest.mark.generated
@pytest.mark.error_path
def test_extraction_exception_handling():
    """Verify that exceptions during extraction are caught, logged with the site name, and an empty dictionary is returned."""
    logger = Mock()
    site = Mock()
    site.name = "TestSite"
    error_msg = "Parsing failed"
    
    with patch('maigret.checking.extract', side_effect=Exception(error_msg)):
        result = extract_ids_data("<html>...</html>", logger, site)
        
    assert result == {}
    logger.warning.assert_called_once()
    call_args = logger.warning.call_args[0][0]
    assert "TestSite" in call_args
    assert error_msg in call_args

@pytest.mark.generated
@pytest.mark.edge_case
def test_empty_html_input():
    """Verify that empty HTML input is handled gracefully (returning whatever the extractor returns, usually an empty dict)."""
    logger = Mock()
    site = Mock()
    site.name = "TestSite"
    
    with patch('maigret.checking.extract', return_value={}):
        result = extract_ids_data("", logger, site)
        
    assert result == {}
    assert logger.warning.called is False

@pytest.mark.generated
@pytest.mark.edge_case
def test_none_html_input():
    """Verify that passing None as html_text (which might cause a TypeError in the extractor) is caught by the exception handler."""
    logger = Mock()
    site = Mock()
    site.name = "TestSite"
    
    with patch('maigret.checking.extract', side_effect=TypeError("Expected string or bytes-like object")):
        result = extract_ids_data(None, logger, site)
        
    assert result == {}
    assert logger.warning.called is True
