# ROOST_METHOD_HASH=maigret_67573ae824
# ROOST_METHOD_SIG_HASH=maigret_9817f13319

"""Tests for `maigret.checking.maigret`.

Auto-generated by roost-pytest. Re-generate when the source
changes; see the run report for generation details.
"""
# Source: maigret/checking.py:746-924
# Scenarios:
#   - [happy_path] happy_path_multiple_sites: Verify that maigret correctly orchestrates a search across multiple sites and returns the aggregated results.
#   - [happy_path] retry_on_failure: Verify that maigret correctly retries failed searches when the error is not permanent and retries are enabled.
#   - [happy_path] proxy_initialization: Verify that the various checkers are correctly initialized with the provided proxy, tor_proxy, and i2p_proxy.
#   - [edge_case] id_type_filtering: Verify that sites with an identifier type different from the requested one are correctly marked as illegal.
#   - [happy_path] domain_checking_enabled: Verify that domain resolution is enabled and the DNS checker is initialized when `check_domains` is True.
#   - [happy_path] parsing_enabled_passed: Verify that the `is_parsing_enabled` flag is correctly propagated through the options to the site checking logic.

import sys
from unittest import mock
import logging

# Mock missing dependencies before importing maigret
sys.modules['aiodns'] = mock.Mock()

m_alive_progress = mock.Mock()
m_alive_progress.alive_bar = mock.MagicMock()
sys.modules['alive_progress'] = m_alive_progress

sys.modules['socid_extractor'] = mock.Mock()
sys.modules['python_socks'] = mock.Mock()
sys.modules['python_socks._errors'] = mock.Mock()
sys.modules['colorama'] = mock.Mock()
sys.modules['requests'] = mock.Mock()
sys.modules['curl_cffi'] = mock.Mock()
sys.modules['xmind'] = mock.Mock()
sys.modules['jinja2'] = mock.Mock()
sys.modules['lxml'] = mock.Mock()
sys.modules['lxml.etree'] = mock.Mock()
sys.modules['cloudscraper'] = mock.Mock()
sys.modules['future'] = mock.Mock()
sys.modules['aiohttp_socks'] = mock.Mock()

import pytest
import asyncio
from maigret.checking import maigret
from maigret.sites import MaigretSite
from maigret.result import MaigretCheckResult, MaigretCheckStatus
from maigret.errors import CheckError

async def async_gen(items):
    for item in items:
        yield item

@pytest.mark.generated
@pytest.mark.happy_path
def test_happy_path_multiple_sites():
    """Verify that maigret correctly orchestrates a search across multiple sites and returns the aggregated results."""
    async def _t():
        logger = mock.Mock()
        logger.level = logging.INFO
        query_notify = mock.Mock()
        
        site1 = MaigretSite("site1", {"urlMain": "https://site1.com", "url": "https://site1.com/{username}"})
        site2 = MaigretSite("site2", {"urlMain": "https://site2.com", "url": "https://site2.com/{username}"})
        site_dict = {"site1": site1, "site2": site2}
        
        res1 = {"site": site1, "status": MaigretCheckResult("testuser", "site1", "", MaigretCheckStatus.CLAIMED)}
        res2 = {"site": site2, "status": MaigretCheckResult("testuser", "site2", "", MaigretCheckStatus.AVAILABLE)}
        
        async def mock_run(queries):
            yield ("site1", res1)
            yield ("site2", res2)
            
        with mock.patch("maigret.checking.AsyncioQueueGeneratorExecutor") as MockExecutor, \
             mock.patch("maigret.checking.SimpleAiohttpChecker") as MockSimple, \
             mock.patch("maigret.checking.CheckerMock") as MockCheckerMock:
            
            MockExecutor.return_value.run.side_effect = mock_run
            MockSimple.return_value.close = mock.AsyncMock()
            MockCheckerMock.return_value.close = mock.AsyncMock()
            
            results = await maigret("testuser", site_dict, logger, query_notify=query_notify, no_progressbar=True)
            
            assert "site1" in results
            assert "site2" in results
            assert results["site1"]["status"].status == MaigretCheckStatus.CLAIMED
            assert results["site2"]["status"].status == MaigretCheckStatus.AVAILABLE
            query_notify.start.assert_called_with("testuser", "username")

    asyncio.run(_t())

@pytest.mark.generated
@pytest.mark.happy_path
def test_retry_on_failure():
    """Verify that maigret correctly retries failed searches when the error is not permanent and retries are enabled."""
    async def _t():
        logger = mock.Mock()
        logger.level = logging.INFO
        site1 = MaigretSite("site1", {"urlMain": "https://site1.com", "url": "https://site1.com/{username}"})
        site_dict = {"site1": site1}
        
        fail_res = {"site": site1, "status": MaigretCheckResult("testuser", "site1", "", MaigretCheckStatus.UNKNOWN, error=CheckError("Request failed"))}
        success_res = {"site": site1, "status": MaigretCheckResult("testuser", "site1", "", MaigretCheckStatus.CLAIMED)}
        
        call_count = 0
        async def mock_run(queries):
            nonlocal call_count
            call_count += 1
            if call_count == 1:
                yield ("site1", fail_res)
            else:
                yield ("site1", success_res)
                
        with mock.patch("maigret.checking.AsyncioQueueGeneratorExecutor") as MockExecutor, \
             mock.patch("maigret.checking.SimpleAiohttpChecker") as MockSimple, \
             mock.patch("maigret.checking.CheckerMock") as MockCheckerMock:
            
            MockExecutor.return_value.run.side_effect = mock_run
            MockSimple.return_value.close = mock.AsyncMock()
            MockCheckerMock.return_value.close = mock.AsyncMock()
            
            results = await maigret("testuser", site_dict, logger, retries=1, no_progressbar=True)
            
            assert call_count == 2
            assert results["site1"]["status"].status == MaigretCheckStatus.CLAIMED

    asyncio.run(_t())

@pytest.mark.generated
@pytest.mark.happy_path
def test_proxy_initialization():
    """Verify that the various checkers are correctly initialized with the provided proxy, tor_proxy, and i2p_proxy."""
    async def _t():
        logger = mock.Mock()
        logger.level = logging.INFO
        site_dict = {}
        
        with mock.patch("maigret.checking.SimpleAiohttpChecker") as MockSimple, \
             mock.patch("maigret.checking.ProxiedAiohttpChecker") as MockProxied, \
             mock.patch("maigret.checking.AsyncioQueueGeneratorExecutor") as MockExecutor, \
             mock.patch("maigret.checking.CheckerMock") as MockCheckerMock:
            
            MockExecutor.return_value.run.side_effect = lambda q: async_gen([])
            MockSimple.return_value.close = mock.AsyncMock()
            MockProxied.return_value.close = mock.AsyncMock()
            MockCheckerMock.return_value.close = mock.AsyncMock()
            
            await maigret("testuser", site_dict, logger, 
                          proxy="http://proxy", 
                          tor_proxy="socks5://tor", 
                          i2p_proxy="http://i2p", 
                          no_progressbar=True)
            
            MockSimple.assert_called_once()
            assert MockSimple.call_args[1]['proxy'] == "http://proxy"
            
            assert MockProxied.call_count == 2
            proxies = [call[1]['proxy'] for call in MockProxied.call_args_list]
            assert "socks5://tor" in proxies
            assert "http://i2p" in proxies

    asyncio.run(_t())

@pytest.mark.generated
@pytest.mark.edge_case
def test_id_type_filtering():
    """Verify that sites with an identifier type different from the requested one are correctly marked as illegal."""
    async def _t():
        logger = mock.Mock()
        logger.level = logging.INFO
        site1 = MaigretSite("site1", {"urlMain": "https://site1.com", "url": "https://site1.com/{username}", "type": "username", "checkType": "status_code"})
        site2 = MaigretSite("site2", {"urlMain": "https://site2.com", "url": "https://site2.com/{username}", "type": "email", "checkType": "status_code"})
        site_dict = {"site1": site1, "site2": site2}
        
        # We need to let check_site_for_username run to see the ILLEGAL status
        from maigret.checking import check_site_for_username
        
        async def mock_run(queries):
            for f, args, kwargs in queries:
                yield await f(*args, **kwargs)
                
        with mock.patch("maigret.checking.AsyncioQueueGeneratorExecutor") as MockExecutor, \
             mock.patch("maigret.checking.SimpleAiohttpChecker") as MockSimple, \
             mock.patch("maigret.checking.CheckerMock") as MockCheckerMock:
            
            MockSimple.return_value.check = mock.AsyncMock(return_value=("", 200, None))
            MockSimple.return_value.close = mock.AsyncMock()
            MockCheckerMock.return_value.close = mock.AsyncMock()
            
            MockExecutor.return_value.run.side_effect = mock_run
            
            results = await maigret("testuser", site_dict, logger, id_type="username", no_progressbar=True)
            
            assert results["site2"]["status"].status == MaigretCheckStatus.ILLEGAL
            assert "Unsupported identifier type" in results["site2"]["status"].error.type

    asyncio.run(_t())

@pytest.mark.generated
@pytest.mark.happy_path
def test_domain_checking_enabled():
    """Verify that domain resolution is enabled and the DNS checker is initialized when `check_domains` is True."""
    async def _t():
        logger = mock.Mock()
        logger.level = logging.INFO
        site1 = MaigretSite("site1", {"urlMain": "https://site1.com", "url": "https://site1.com/{username}"})
        site_dict = {"site1": site1}
        
        with mock.patch("maigret.checking.AiodnsDomainResolver") as MockDNS, \
             mock.patch("maigret.checking.AsyncioQueueGeneratorExecutor") as MockExecutor, \
             mock.patch("maigret.checking.SimpleAiohttpChecker") as MockSimple, \
             mock.patch("maigret.checking.CheckerMock") as MockCheckerMock:
            
            MockExecutor.return_value.run.side_effect = lambda q: async_gen([])
            MockSimple.return_value.close = mock.AsyncMock()
            MockCheckerMock.return_value.close = mock.AsyncMock()
            
            await maigret("testuser", site_dict, logger, check_domains=True, no_progressbar=True)
            
            MockDNS.assert_called_once_with(logger=logger)
            
            # Verify it's in the checkers passed to the executor
            args_list = MockExecutor.return_value.run.call_args[0][0]
            f, args, kwargs = args_list[0]
            options = args[2]
            assert options["checkers"]["dns"] == MockDNS.return_value

    asyncio.run(_t())

@pytest.mark.generated
@pytest.mark.happy_path
def test_parsing_enabled_passed():
    """Verify that the `is_parsing_enabled` flag is correctly propagated through the options to the site checking logic."""
    async def _t():
        logger = mock.Mock()
        logger.level = logging.INFO
        site1 = MaigretSite("site1", {"urlMain": "https://site1.com", "url": "https://site1.com/{username}"})
        site_dict = {"site1": site1}
        
        with mock.patch("maigret.checking.AsyncioQueueGeneratorExecutor") as MockExecutor, \
             mock.patch("maigret.checking.SimpleAiohttpChecker") as MockSimple, \
             mock.patch("maigret.checking.CheckerMock") as MockCheckerMock:
            
            MockExecutor.return_value.run.side_effect = lambda q: async_gen([])
            MockSimple.return_value.close = mock.AsyncMock()
            MockCheckerMock.return_value.close = mock.AsyncMock()
            
            await maigret("testuser", site_dict, logger, is_parsing_enabled=True, no_progressbar=True)
            
            args_list = MockExecutor.return_value.run.call_args[0][0]
            f, args, kwargs = args_list[0]
            options = args[2]
            assert options["parsing"] is True

    asyncio.run(_t())
