# ROOST_METHOD_HASH=SimpleAiohttpChecker.prepare_815fa75425
# ROOST_METHOD_SIG_HASH=SimpleAiohttpChecker.prepare_ce92c43645

"""Tests for `maigret.checking.SimpleAiohttpChecker.prepare`.

Auto-generated by roost-pytest. Re-generate when the source
changes; see the run report for generation details.
"""
# Source: maigret/checking.py:67-74
# Scenarios:
#   - [happy_path] test_prepare_sets_all_attributes: Verify that all parameters passed to prepare are correctly stored in the instance attributes.
#   - [happy_path] test_prepare_sets_defaults: Verify that default values are used when optional arguments are omitted in the prepare call.
#   - [happy_path] test_prepare_overwrites_previous_values: Verify that subsequent calls to prepare overwrite previous values, including resetting omitted arguments to their defaults.
#   - [edge_case] test_prepare_with_empty_values: Verify that passing empty strings or collections for parameters works as expected.

import sys
from unittest.mock import MagicMock

# Mock missing dependencies before importing maigret.checking
class MockModule(MagicMock):
    def __getattr__(self, name):
        return MagicMock()

missing_mods = [
    'aiodns', 'alive_progress', 'socid_extractor', 'python_socks', 
    'aiohttp_socks', 'colorama', 'xmind', 'jinja2', 'requests', 
    'bs4', 'lxml', 'yaml', 'tqdm', 'cloudscraper', 'fake_useragent',
    'aiohttp', 'aiohttp.client_exceptions'
]

for mod in missing_mods:
    sys.modules[mod] = MockModule()

import pytest
from maigret.checking import SimpleAiohttpChecker

@pytest.mark.generated
@pytest.mark.happy_path
def test_prepare_sets_all_attributes():
    """Verify that all parameters passed to prepare are correctly stored in the instance attributes."""
    checker = SimpleAiohttpChecker()
    checker.prepare(
        url="https://example.com",
        headers={"User-Agent": "test"},
        allow_redirects=False,
        timeout=5,
        method="POST",
        payload={"key": "value"}
    )
    assert checker.url == "https://example.com"
    assert checker.headers == {"User-Agent": "test"}
    assert checker.allow_redirects is False
    assert checker.timeout == 5
    assert checker.method == "POST"
    assert checker.payload == {"key": "value"}

@pytest.mark.generated
@pytest.mark.happy_path
def test_prepare_sets_defaults():
    """Verify that default values are used when optional arguments are omitted in the prepare call."""
    checker = SimpleAiohttpChecker()
    checker.prepare(url="https://example.com")
    assert checker.url == "https://example.com"
    assert checker.headers is None
    assert checker.allow_redirects is True
    assert checker.timeout == 0
    assert checker.method == "get"
    assert checker.payload is None

@pytest.mark.generated
@pytest.mark.happy_path
def test_prepare_overwrites_previous_values():
    """Verify that subsequent calls to prepare overwrite previous values, including resetting omitted arguments to their defaults."""
    checker = SimpleAiohttpChecker()
    checker.prepare(url="https://old.com", timeout=5, method="POST")
    
    # Verify initial state
    assert checker.url == "https://old.com"
    assert checker.timeout == 5
    assert checker.method == "POST"
    
    checker.prepare(url="https://new.com", timeout=10)
    assert checker.url == "https://new.com"
    assert checker.timeout == 10
    assert checker.method == "get"  # reset to default

@pytest.mark.generated
@pytest.mark.edge_case
def test_prepare_with_empty_values():
    """Verify that passing empty strings or collections for parameters works as expected."""
    checker = SimpleAiohttpChecker()
    checker.prepare(url="", headers={}, payload={})
    assert checker.url == ""
    assert checker.headers == {}
    assert checker.payload == {}
