# ROOST_METHOD_HASH=check_2a51c5e77b
# ROOST_METHOD_SIG_HASH=check_7cf19bb4aa

# NB: existing tests detected for this symbol.
#
# Hand-written test(s) found (no ROOST_METHOD_HASH header):
#   - tests/test_checking.py
# This file was generated ALONGSIDE those — the user's
# tests are kept untouched. The scenarios here may
# differ from what the hand-written file covers.

"""Tests for `maigret.checking.CurlCffiChecker.check`.

Auto-generated by roost-pytest. Re-generate when the source
changes; see the run report for generation details.
"""
# Source: maigret/checking.py:247-287
# Scenarios:
#   - [happy_path] happy_path_head: Verify that the checker correctly handles HEAD requests and returns the expected tuple.
#   - [edge_case] connection_lost_error: Verify that a status code of 0 from curl_cffi is treated as a 'Connection lost' error.
#   - [error_path] timeout_error: Verify that asyncio.TimeoutError is caught and converted into a CheckError.
#   - [error_path] unexpected_exception_handling: Verify that generic exceptions are caught and converted into an 'Unexpected' CheckError.
#   - [error_path] keyboard_interrupt_handling: Verify that KeyboardInterrupt is caught and converted into an 'Interrupted' CheckError.

import sys
from unittest.mock import MagicMock, AsyncMock, patch

# Mock missing dependencies before importing maigret.checking
for mod in [
    'aiodns', 'alive_progress', 'socid_extractor', 'python_socks', 
    'colorama', 'aiohttp', 'aiohttp.client_exceptions', 'xmind', 
    'jinja2', 'requests', 'bs4', 'lxml', 'yaml', 'future', 'mock',
    'cloudscraper', 'requests_futures', 'pycountry', 'idna', 'tldextract'
]:
    sys.modules[mod] = MagicMock()

import asyncio
import pytest
from maigret.checking import CurlCffiChecker
from maigret.errors import CheckError

class _FakeCurlResponse:
    def __init__(self, text, status_code):
        self.text = text
        self.status_code = status_code

@pytest.fixture
def mock_session():
    session = MagicMock()
    session.get = AsyncMock()
    session.post = AsyncMock()
    session.head = AsyncMock()
    
    # Mocking the async context manager
    session.__aenter__ = AsyncMock(return_value=session)
    session.__aexit__ = AsyncMock(return_value=None)
    
    return session

@pytest.fixture
def patch_session(mock_session):
    # Use create=True because CurlCffiAsyncSession might not be defined if curl_cffi is not installed
    with patch('maigret.checking.CurlCffiAsyncSession', return_value=mock_session, create=True):
        yield mock_session

@pytest.mark.generated
@pytest.mark.happy_path
def test_happy_path_head(patch_session):
    """Verify that the checker correctly handles HEAD requests and returns the expected tuple."""
    async def _t():
        checker = CurlCffiChecker(browser_emulate='chrome')
        checker.prepare(url='https://example.com', method='head')
        patch_session.head.return_value = _FakeCurlResponse(text='', status_code=200)
        
        result = await checker.check()
        
        assert result == ('', 200, None)
        assert patch_session.head.called

    asyncio.run(_t())

@pytest.mark.generated
@pytest.mark.edge_case
def test_connection_lost_error(patch_session):
    """Verify that a status code of 0 from curl_cffi is treated as a 'Connection lost' error."""
    async def _t():
        checker = CurlCffiChecker()
        checker.prepare(url='https://example.com')
        patch_session.get.return_value = _FakeCurlResponse(text='', status_code=0)
        
        result = await checker.check()
        
        assert result[0] == ''
        assert result[1] == 0
        assert isinstance(result[2], CheckError)
        assert result[2].type == 'Connection lost'

    asyncio.run(_t())

@pytest.mark.generated
@pytest.mark.error_path
def test_timeout_error(patch_session):
    """Verify that asyncio.TimeoutError is caught and converted into a CheckError."""
    async def _t():
        checker = CurlCffiChecker()
        checker.prepare(url='https://example.com')
        patch_session.get.side_effect = asyncio.TimeoutError('Connection timed out')
        
        result = await checker.check()
        
        assert result[0] is None
        assert result[1] == 0
        assert isinstance(result[2], CheckError)
        assert result[2].type == 'Request timeout'
        assert result[2].desc == 'Connection timed out'

    asyncio.run(_t())

@pytest.mark.generated
@pytest.mark.error_path
def test_unexpected_exception_handling(patch_session):
    """Verify that generic exceptions are caught and converted into an 'Unexpected' CheckError."""
    async def _t():
        checker = CurlCffiChecker()
        checker.prepare(url='https://example.com')
        patch_session.get.side_effect = Exception('Something went wrong')
        
        result = await checker.check()
        
        assert result[0] is None
        assert result[1] == 0
        assert isinstance(result[2], CheckError)
        assert result[2].type == 'Unexpected'
        assert result[2].desc == 'Something went wrong'

    asyncio.run(_t())

@pytest.mark.generated
@pytest.mark.error_path
def test_keyboard_interrupt_handling(patch_session):
    """Verify that KeyboardInterrupt is caught and converted into an 'Interrupted' CheckError."""
    async def _t():
        checker = CurlCffiChecker()
        checker.prepare(url='https://example.com')
        patch_session.get.side_effect = KeyboardInterrupt()
        
        result = await checker.check()
        
        assert result[0] is None
        assert result[1] == 0
        assert isinstance(result[2], CheckError)
        assert result[2].type == 'Interrupted'

    asyncio.run(_t())
