# ROOST_METHOD_HASH=close_39a71cbfe4
# ROOST_METHOD_SIG_HASH=close_ec965e14c1

"""Tests for `maigret.checking.SimpleAiohttpChecker.close`.

Auto-generated by roost-pytest. Re-generate when the source
changes; see the run report for generation details.
"""
# Source: maigret/checking.py:76-77
# Scenarios:
#   - [happy_path] close_new_instance: Verify that close() can be called on a newly initialized checker.
#   - [happy_path] close_after_prepare: Verify that close() can be called after the checker has been prepared.
#   - [edge_case] close_idempotency: Verify that close() can be called multiple times without side effects or errors.

import sys
from unittest.mock import MagicMock

# Mock missing dependencies before importing the SUT
for module in [
    'aiodns', 'alive_progress', 'socid_extractor', 'python_socks', 
    'aiohttp_socks', 'colorama', 'future', 'requests', 'cloudscraper',
    'bs4', 'lxml', 'networkx', 'matplotlib', 'pandas', 'jinja2',
    'xmind', 'curl_cffi', 'curl_cffi.requests'
]:
    sys.modules[module] = MagicMock()

import pytest
import asyncio
from maigret.checking import SimpleAiohttpChecker

@pytest.mark.generated
@pytest.mark.happy_path
def test_close_new_instance():
    """Verify that close() can be called on a newly initialized checker."""
    async def _t():
        checker = SimpleAiohttpChecker()
        result = await checker.close()
        assert result is None
    
    asyncio.run(_t())

@pytest.mark.generated
@pytest.mark.happy_path
def test_close_after_prepare():
    """Verify that close() can be called after the checker has been prepared."""
    async def _t():
        checker = SimpleAiohttpChecker()
        checker.prepare(url='http://example.com')
        result = await checker.close()
        assert result is None
    
    asyncio.run(_t())

@pytest.mark.generated
@pytest.mark.edge_case
def test_close_idempotency():
    """Verify that close() can be called multiple times without side effects or errors."""
    async def _t():
        checker = SimpleAiohttpChecker()
        await checker.close()
        await checker.close()
    
    asyncio.run(_t())
