# ROOST_METHOD_HASH=ProxiedAiohttpChecker.__init___20c15753fd
# ROOST_METHOD_SIG_HASH=ProxiedAiohttpChecker.__init___dc2abf071b

"""Tests for `maigret.checking.ProxiedAiohttpChecker.__init__`.

Auto-generated by roost-pytest. Re-generate when the source
changes; see the run report for generation details.
"""
# Source: maigret/checking.py:177-180
# Scenarios:
#   - [happy_path] test_init_with_all_args: Verify that proxy, cookie_jar, and logger are correctly assigned when provided as keyword arguments.
#   - [happy_path] test_init_defaults: Verify that logger defaults to a Mock object and cookie_jar defaults to None when omitted.
#   - [edge_case] test_init_extra_args_ignored: Verify that positional arguments and unexpected keyword arguments are accepted but not stored on the instance.
#   - [regression] test_init_no_super_call_side_effect: Verify that base class attributes (url, headers, timeout, etc.) are NOT initialized, confirming super().__init__ is not called (current behavior).

import sys
from unittest.mock import MagicMock

# Mock missing dependencies before importing maigret.checking
sys.modules['aiodns'] = MagicMock()
sys.modules['alive_progress'] = MagicMock()
sys.modules['python_socks'] = MagicMock()
sys.modules['socid_extractor'] = MagicMock()
sys.modules['colorama'] = MagicMock()
sys.modules['aiohttp'] = MagicMock()
sys.modules['aiohttp.client_exceptions'] = MagicMock()
sys.modules['xmind'] = MagicMock()

# Mock internal modules that have many dependencies
sys.modules['maigret.maigret'] = MagicMock()
sys.modules['maigret.report'] = MagicMock()
sys.modules['maigret.notify'] = MagicMock()

import pytest
from unittest.mock import Mock
from maigret.checking import ProxiedAiohttpChecker

@pytest.mark.generated
@pytest.mark.happy_path
def test_init_with_all_args():
    """
    Verify that proxy, cookie_jar, and logger are correctly assigned when provided as keyword arguments.
    """
    mock_cookie_jar = Mock()
    mock_logger = Mock()
    checker = ProxiedAiohttpChecker(proxy="http://1.2.3.4:8080", cookie_jar=mock_cookie_jar, logger=mock_logger)
    
    assert checker.proxy == "http://1.2.3.4:8080"
    assert checker.cookie_jar == mock_cookie_jar
    assert checker.logger == mock_logger

@pytest.mark.generated
@pytest.mark.happy_path
def test_init_defaults():
    """
    Verify that logger defaults to a Mock object and cookie_jar defaults to None when omitted.
    """
    checker = ProxiedAiohttpChecker(proxy="socks5://localhost:9050")
    
    assert checker.proxy == "socks5://localhost:9050"
    assert checker.cookie_jar is None
    assert isinstance(checker.logger, Mock)

@pytest.mark.generated
@pytest.mark.edge_case
def test_init_extra_args_ignored():
    """
    Verify that positional arguments and unexpected keyword arguments are accepted but not stored on the instance.
    """
    checker = ProxiedAiohttpChecker("pos_arg", proxy="http://p", extra_kwarg="value")
    
    assert checker.proxy == "http://p"
    assert not hasattr(checker, "extra_kwarg")

@pytest.mark.generated
@pytest.mark.regression
def test_init_no_super_call_side_effect():
    """
    Verify that base class attributes (url, headers, timeout, etc.) are NOT initialized, confirming super().__init__ is not called (current behavior).
    """
    checker = ProxiedAiohttpChecker()
    
    # These attributes are initialized in SimpleAiohttpChecker.__init__
    # but ProxiedAiohttpChecker.__init__ does not call super().__init__()
    assert not hasattr(checker, "url")
    assert not hasattr(checker, "headers")
    assert not hasattr(checker, "timeout")
    assert not hasattr(checker, "allow_redirects")
    assert not hasattr(checker, "method")
    assert not hasattr(checker, "payload")
