# ROOST_METHOD_HASH=detect_error_page_1b6a5901f4
# ROOST_METHOD_SIG_HASH=detect_error_page_fa12a12d96

# NB: existing tests detected for this symbol.
#
# Hand-written test(s) found (no ROOST_METHOD_HASH header):
#   - tests/test_checking.py
# This file was generated ALONGSIDE those — the user's
# tests are kept untouched. The scenarios here may
# differ from what the hand-written file covers.

"""Tests for `maigret.checking.detect_error_page`.

Auto-generated by roost-pytest. Re-generate when the source
changes; see the run report for generation details.
"""
# Source: maigret/checking.py:306-331
# Scenarios:
#   - [happy_path] common_error_detection_cloudflare: Verify that common errors (like Cloudflare) are detected via errors.detect even if status code is 200.
#   - [edge_case] precedence_site_flag_over_all: Verify that site-specific fail_flags take precedence over common error detection and status codes.
#   - [edge_case] precedence_common_error_over_403: Verify that common error detection takes precedence over the generic 403 status code check.
#   - [edge_case] status_500_boundary: Verify that status code exactly 500 is correctly identified as a Server error.
#   - [edge_case] status_404_not_an_error: Verify that a 404 status code (without matching error flags) is not treated as an error page.
#   - [edge_case] multiple_matching_site_flags: Verify that if multiple site-specific flags match, the first one in the dictionary is returned.

import sys
from unittest.mock import MagicMock

# Mock missing dependencies before importing maigret
sys.modules['aiodns'] = MagicMock()
sys.modules['alive_progress'] = MagicMock()
sys.modules['socid_extractor'] = MagicMock()
sys.modules['python_socks'] = MagicMock()
sys.modules['python_socks._errors'] = MagicMock()
sys.modules['colorama'] = MagicMock()
sys.modules['mock'] = MagicMock()
sys.modules['xmind'] = MagicMock()
sys.modules['jinja2'] = MagicMock()
sys.modules['cloudscraper'] = MagicMock()

import pytest
from maigret.checking import detect_error_page

@pytest.mark.generated
@pytest.mark.happy_path
def test_common_error_detection_cloudflare():
    """Verify that common errors (like Cloudflare) are detected via errors.detect even if status code is 200."""
    result = detect_error_page("<title>Attention Required! | Cloudflare</title>", 200, {}, False)
    assert result is not None
    assert result.type == "Captcha"
    assert result.desc == "Cloudflare"

@pytest.mark.generated
@pytest.mark.edge_case
def test_precedence_site_flag_over_all():
    """Verify that site-specific fail_flags take precedence over common error detection and status codes."""
    # html_text contains both a site-specific flag and a common error flag.
    html_text = "<title>Attention Required! | Cloudflare</title> Site Flag"
    result = detect_error_page(html_text, 403, {"Site Flag": "Site Message"}, False)
    assert result is not None
    assert result.type == "Site-specific"
    assert result.desc == "Site Message"

@pytest.mark.generated
@pytest.mark.edge_case
def test_precedence_common_error_over_403():
    """Verify that common error detection takes precedence over the generic 403 status code check."""
    # html_text contains a common error flag, and status_code is 403.
    result = detect_error_page("<title>Attention Required! | Cloudflare</title>", 403, {}, False)
    assert result is not None
    assert result.type == "Captcha"
    assert result.desc == "Cloudflare"

@pytest.mark.generated
@pytest.mark.edge_case
def test_status_500_boundary():
    """Verify that status code exactly 500 is correctly identified as a Server error."""
    result = detect_error_page("", 500, {}, False)
    assert result is not None
    assert result.type == "Server"
    assert "500" in result.desc

@pytest.mark.generated
@pytest.mark.edge_case
def test_status_404_not_an_error():
    """Verify that a 404 status code (without matching error flags) is not treated as an error page."""
    result = detect_error_page("Not Found", 404, {}, False)
    assert result is None

@pytest.mark.generated
@pytest.mark.edge_case
def test_multiple_matching_site_flags():
    """Verify that if multiple site-specific flags match, the first one in the dictionary is returned."""
    result = detect_error_page("flag1 flag2", 200, {"flag1": "msg1", "flag2": "msg2"}, False)
    assert result is not None
    assert result.desc == "msg1"
