# ROOST_METHOD_HASH=close_e91331198c
# ROOST_METHOD_SIG_HASH=close_ec965e14c1

"""Tests for `maigret.checking.CheckerMock.close`.

Auto-generated by roost-pytest. Re-generate when the source
changes; see the run report for generation details.
"""
# Source: maigret/checking.py:301-302
# Scenarios:
#   - [happy_path] test_close_basic: Verify that the close method can be called on a new instance and returns None.
#   - [edge_case] test_close_idempotent: Verify that calling close multiple times is safe and idempotent.
#   - [happy_path] test_close_after_use: Verify that close works correctly after the checker has been used for preparation and checking.

import sys
from unittest.mock import MagicMock

# Mock missing dependencies before importing maigret.checking
def mock_module(name, attrs=None):
    try:
        __import__(name)
    except ImportError:
        m = MagicMock()
        if attrs:
            for attr in attrs:
                setattr(m, attr, MagicMock())
        sys.modules[name] = m

mock_module('aiodns')
mock_module('alive_progress', ['alive_bar'])
mock_module('aiohttp', ['ClientSession', 'TCPConnector', 'http_exceptions'])
mock_module('aiohttp.client_exceptions', ['ClientConnectorError', 'ServerDisconnectedError'])
mock_module('python_socks', ['_errors'])
mock_module('socid_extractor', ['extract'])
mock_module('colorama', ['Fore', 'Style', 'init'])
mock_module('xmind')
mock_module('jinja2', ['Template'])
mock_module('pdfkit')
mock_module('cloudscraper')
mock_module('requests')

import pytest
import asyncio
from maigret.checking import CheckerMock

@pytest.mark.generated
@pytest.mark.happy_path
def test_close_basic():
    """Verify that the close method can be called on a new instance and returns None."""
    checker = CheckerMock()
    
    async def _t():
        result = await checker.close()
        assert result is None
        
    asyncio.run(_t())

@pytest.mark.generated
@pytest.mark.edge_case
def test_close_idempotent():
    """Verify that calling close multiple times is safe and idempotent."""
    checker = CheckerMock()
    
    async def _t():
        await checker.close()
        await checker.close()
        
    asyncio.run(_t())

@pytest.mark.generated
@pytest.mark.happy_path
def test_close_after_use():
    """Verify that close works correctly after the checker has been used for preparation and checking."""
    checker = CheckerMock()
    
    async def _t():
        checker.prepare("http://example.com")
        await checker.check()
        await checker.close()
        
    asyncio.run(_t())
