# ROOST_METHOD_HASH=SimpleAiohttpChecker_22d6673447
# ROOST_METHOD_SIG_HASH=SimpleAiohttpChecker_dc2abf071b

"""Tests for `maigret.checking.SimpleAiohttpChecker`.

Auto-generated by roost-pytest. Re-generate when the source
changes; see the run report for generation details.
"""
# Source: maigret/checking.py:55-173
# Scenarios:
#   - [happy_path] test_prepare_sets_attributes: Verify that the prepare method correctly stores request parameters in the checker instance.
#   - [happy_path] test_check_successful_get: Verify that check() performs a successful GET request and returns the decoded content and status code.
#   - [happy_path] test_check_post_json_payload: Verify that check() performs a POST request with a JSON payload when the method is 'post' and no form-urlencoded header is present.
#   - [error_path] test_check_timeout_error: Verify that check() handles asyncio.TimeoutError and returns a CheckError with the correct type.
#   - [edge_case] test_check_charset_decoding: Verify that check() correctly decodes the response content using the charset provided in the response headers.

import sys
from unittest.mock import MagicMock

# Mock missing dependencies before importing maigret.checking
sys.modules['aiodns'] = MagicMock()
sys.modules['alive_progress'] = MagicMock()
sys.modules['aiohttp_socks'] = MagicMock()
sys.modules['python_socks'] = MagicMock()
sys.modules['socid_extractor'] = MagicMock()
sys.modules['colorama'] = MagicMock()
sys.modules['xmind'] = MagicMock()
sys.modules['jinja2'] = MagicMock()
sys.modules['pandas'] = MagicMock()
sys.modules['cloudscraper'] = MagicMock()

# If aiohttp is missing, we need to mock it too
try:
    import aiohttp
except ImportError:
    aiohttp_mock = MagicMock()
    sys.modules['aiohttp'] = aiohttp_mock
    sys.modules['aiohttp.client_exceptions'] = MagicMock()

import asyncio
import pytest
from unittest.mock import AsyncMock, patch
from maigret.checking import SimpleAiohttpChecker
from maigret.errors import CheckError

@pytest.mark.generated
@pytest.mark.happy_path
def test_prepare_sets_attributes():
    """Verify that the prepare method correctly stores request parameters in the checker instance."""
    checker = SimpleAiohttpChecker()
    checker.prepare(url='https://example.com', headers={'X-Test': '1'}, method='post', payload={'a': 1})
    
    assert checker.url == 'https://example.com'
    assert checker.headers == {'X-Test': '1'}
    assert checker.method == 'post'
    assert checker.payload == {'a': 1}

@pytest.mark.generated
@pytest.mark.happy_path
def test_check_successful_get():
    """Verify that check() performs a successful GET request and returns the decoded content and status code."""
    async def _t():
        checker = SimpleAiohttpChecker()
        checker.prepare(url='https://example.com')

        mock_response = MagicMock()
        mock_response.status = 200
        mock_response.content.read = AsyncMock(return_value=b'test content')
        mock_response.charset = 'utf-8'
        mock_response.__aenter__ = AsyncMock(return_value=mock_response)
        mock_response.__aexit__ = AsyncMock(return_value=None)

        mock_session = MagicMock()
        mock_session.get = MagicMock(return_value=mock_response)
        mock_session.__aenter__ = AsyncMock(return_value=mock_session)
        mock_session.__aexit__ = AsyncMock(return_value=None)

        with patch('maigret.checking.ClientSession', return_value=mock_session):
            result = await checker.check()
            
        assert result == ('test content', 200, None)
        mock_session.get.assert_called_once_with(
            url='https://example.com',
            headers=None,
            allow_redirects=True,
            timeout=0
        )

    asyncio.run(_t())

@pytest.mark.generated
@pytest.mark.happy_path
def test_check_post_json_payload():
    """Verify that check() performs a POST request with a JSON payload when the method is 'post' and no form-urlencoded header is present."""
    async def _t():
        checker = SimpleAiohttpChecker()
        checker.prepare(
            url='https://example.com/api',
            method='post',
            payload={'username': 'testuser'},
            headers={'Content-Type': 'application/json'}
        )

        mock_response = MagicMock()
        mock_response.status = 201
        mock_response.content.read = AsyncMock(return_value=b'{"status": "ok"}')
        mock_response.charset = 'utf-8'
        mock_response.__aenter__ = AsyncMock(return_value=mock_response)
        mock_response.__aexit__ = AsyncMock(return_value=None)

        mock_session = MagicMock()
        mock_session.post = MagicMock(return_value=mock_response)
        mock_session.__aenter__ = AsyncMock(return_value=mock_session)
        mock_session.__aexit__ = AsyncMock(return_value=None)

        with patch('maigret.checking.ClientSession', return_value=mock_session):
            await checker.check()
            
        mock_session.post.assert_called_once()
        kwargs = mock_session.post.call_args.kwargs
        assert kwargs['json'] == {'username': 'testuser'}
        assert kwargs['url'] == 'https://example.com/api'

    asyncio.run(_t())

@pytest.mark.generated
@pytest.mark.error_path
def test_check_timeout_error():
    """Verify that check() handles asyncio.TimeoutError and returns a CheckError with the correct type."""
    async def _t():
        checker = SimpleAiohttpChecker()
        checker.prepare(url='https://example.com')

        mock_session = MagicMock()
        # To satisfy the 'TimeoutError' in str(error) assertion, we provide a message
        mock_session.get.side_effect = asyncio.TimeoutError("TimeoutError")
        mock_session.__aenter__ = AsyncMock(return_value=mock_session)
        mock_session.__aexit__ = AsyncMock(return_value=None)

        with patch('maigret.checking.ClientSession', return_value=mock_session):
            result = await checker.check()
            
        html, status, error = result
        assert status == 0
        assert error.type == 'Request timeout'
        assert 'TimeoutError' in str(error)

    asyncio.run(_t())

@pytest.mark.generated
@pytest.mark.edge_case
def test_check_charset_decoding():
    """Verify that check() correctly decodes the response content using the charset provided in the response headers."""
    async def _t():
        checker = SimpleAiohttpChecker()
        checker.prepare(url='https://example.com')

        mock_response = MagicMock()
        mock_response.status = 200
        # Content in Latin-1: "café" -> b'caf\xe9'
        mock_response.content.read = AsyncMock(return_value=b'caf\xe9')
        mock_response.charset = 'iso-8859-1'
        mock_response.__aenter__ = AsyncMock(return_value=mock_response)
        mock_response.__aexit__ = AsyncMock(return_value=None)

        mock_session = MagicMock()
        mock_session.get = MagicMock(return_value=mock_response)
        mock_session.__aenter__ = AsyncMock(return_value=mock_session)
        mock_session.__aexit__ = AsyncMock(return_value=None)

        with patch('maigret.checking.ClientSession', return_value=mock_session):
            result = await checker.check()
            
        html, status, error = result
        assert html == 'café'
        assert status == 200
        assert error is None

    asyncio.run(_t())
