# ROOST_METHOD_HASH=AiodnsDomainResolver_8d9fc2e8bd
# ROOST_METHOD_SIG_HASH=AiodnsDomainResolver_dc2abf071b

"""Tests for `maigret.checking.AiodnsDomainResolver`.

Auto-generated by roost-pytest. Re-generate when the source
changes; see the run report for generation details.
"""
# Source: maigret/checking.py:183-211
# Scenarios:
#   - [happy_path] test_prepare: Verify that the prepare method correctly stores the URL.
#   - [happy_path] test_check_success: Verify that check returns the resolved IP address and status 200 when the DNS query is successful.
#   - [error_path] test_check_dns_error: Verify that check returns status 404 and no error when a DNSError occurs.
#   - [error_path] test_check_unexpected_exception: Verify that check returns status 404 and a CheckError when an unexpected exception occurs during the query.

import sys
from unittest.mock import MagicMock, Mock, AsyncMock, patch
from importlib.machinery import ModuleSpec

class MockLoader:
    def create_module(self, spec):
        m = MagicMock()
        m.__name__ = spec.name
        m.__loader__ = self
        m.__spec__ = spec
        m.__path__ = []
        return m
    def exec_module(self, module):
        pass

class MockFinder:
    def find_spec(self, fullname, path, target=None):
        if fullname.startswith('maigret') or fullname in sys.modules:
            return None
        return ModuleSpec(fullname, MockLoader(), is_package=True)

sys.meta_path.insert(0, MockFinder())

# Specific setup for aiodns
import aiodns
aiodns.error = MagicMock()
aiodns.error.DNSError = type('DNSError', (Exception,), {})

# Specific setup for aiohttp
import aiohttp
aiohttp.ClientSession = MagicMock
aiohttp.TCPConnector = MagicMock
aiohttp.http_exceptions = MagicMock

import aiohttp.client_exceptions
aiohttp.client_exceptions.ClientConnectorError = type('ClientConnectorError', (Exception,), {})
aiohttp.client_exceptions.ServerDisconnectedError = type('ServerDisconnectedError', (Exception,), {})

import pytest
import asyncio
from maigret.checking import AiodnsDomainResolver
from maigret.errors import CheckError

@pytest.mark.generated
@pytest.mark.happy_path
def test_prepare():
    """Verify that the prepare method correctly stores the URL."""
    with patch('maigret.checking.aiodns.DNSResolver'):
        async def _t():
            checker = AiodnsDomainResolver()
            checker.prepare("example.com")
            assert checker.url == "example.com"
        
        asyncio.run(_t())

@pytest.mark.generated
@pytest.mark.happy_path
def test_check_success():
    """Verify that check returns the resolved IP address and status 200 when the DNS query is successful."""
    async def _t():
        with patch('maigret.checking.aiodns.DNSResolver') as mock_resolver_class:
            mock_resolver = mock_resolver_class.return_value
            mock_resolver.query = AsyncMock(return_value=[Mock(host="1.2.3.4")])
            
            checker = AiodnsDomainResolver()
            checker.prepare("example.com")
            
            result = await checker.check()
            assert result == ("1.2.3.4", 200, None)
            
    asyncio.run(_t())

@pytest.mark.generated
@pytest.mark.error_path
def test_check_dns_error():
    """Verify that check returns status 404 and no error when a DNSError occurs."""
    async def _t():
        with patch('maigret.checking.aiodns.DNSResolver') as mock_resolver_class:
            mock_resolver = mock_resolver_class.return_value
            mock_resolver.query = AsyncMock(side_effect=aiodns.error.DNSError())
            
            checker = AiodnsDomainResolver()
            checker.prepare("nonexistent.example.com")
            
            result = await checker.check()
            assert result == ("", 404, None)
            
    asyncio.run(_t())

@pytest.mark.generated
@pytest.mark.error_path
def test_check_unexpected_exception():
    """Verify that check returns status 404 and a CheckError when an unexpected exception occurs during the query."""
    async def _t():
        with patch('maigret.checking.aiodns.DNSResolver') as mock_resolver_class:
            mock_resolver = mock_resolver_class.return_value
            mock_resolver.query = AsyncMock(side_effect=RuntimeError("Unexpected"))
            
            mock_logger = Mock()
            checker = AiodnsDomainResolver(logger=mock_logger)
            checker.prepare("example.com")
            
            result = await checker.check()
            
            assert result[0] == ""
            assert result[1] == 404
            assert isinstance(result[2], CheckError)
            assert result[2].type == 'DNS resolve error'
            assert mock_logger.error.called
            
    asyncio.run(_t())
