# ROOST_METHOD_HASH=CurlCffiChecker.prepare_815fa75425
# ROOST_METHOD_SIG_HASH=CurlCffiChecker.prepare_ce92c43645

# NB: existing tests detected for this symbol.
#
# Hand-written test(s) found (no ROOST_METHOD_HASH header):
#   - tests/test_checking.py
# This file was generated ALONGSIDE those — the user's
# tests are kept untouched. The scenarios here may
# differ from what the hand-written file covers.

"""Tests for `maigret.checking.CurlCffiChecker.prepare`.

Auto-generated by roost-pytest. Re-generate when the source
changes; see the run report for generation details.
"""
# Source: maigret/checking.py:235-242
# Scenarios:
#   - [happy_path] test_prepare_sets_attributes: Verify that prepare correctly assigns all its arguments to the corresponding instance attributes.
#   - [happy_path] test_prepare_integration_head_method: Verify that calling prepare with method='head' results in a HEAD request being executed when check() is called.
#   - [happy_path] test_prepare_integration_custom_timeout: Verify that a non-zero timeout passed to prepare is correctly forwarded to the session in check().
#   - [edge_case] test_prepare_integration_default_timeout: Verify that the default timeout=0 in prepare is translated to a default of 10 seconds in the session call within check().
#   - [happy_path] test_prepare_integration_disallow_redirects: Verify that allow_redirects=False passed to prepare is correctly forwarded to the session in check().
#   - [edge_case] test_prepare_integration_method_case_insensitivity: Verify that prepare handles uppercase method names correctly by ensuring check() performs the expected request type.

import sys
from unittest.mock import MagicMock

# Mock external dependencies to avoid ModuleNotFoundError during import
EXT_MOCKS = [
    'aiodns', 'alive_progress', 'socid_extractor', 'python_socks',
    'aiohttp', 'aiohttp.client_exceptions', 'curl_cffi', 'curl_cffi.requests',
    'colorama', 'xmind', 'cloudscraper', 'jinja2', 'future', 'future.utils',
    'requests', 'requests_futures', 'torrequest', 'selenium', 'webdriver_manager'
]

for mod in EXT_MOCKS:
    if mod not in sys.modules:
        sys.modules[mod] = MagicMock()

import pytest
import asyncio
from unittest.mock import Mock
from maigret.checking import CurlCffiChecker

# --- Fakes for curl_cffi ---

class _FakeCurlResponse:
    """Fake response object for curl_cffi."""
    def __init__(self, text="ok", status_code=200):
        self.text = text
        self.status_code = status_code

class _FakeCurlSession:
    """Captures the kwargs of the last .get/.post/.head call for assertions."""
    last_method = None
    last_kwargs = None

    async def __aenter__(self):
        return self

    async def __aexit__(self, exc_type, exc, tb):
        return False

    async def get(self, **kwargs):
        type(self).last_method = 'get'
        type(self).last_kwargs = kwargs
        return _FakeCurlResponse()

    async def post(self, **kwargs):
        type(self).last_method = 'post'
        type(self).last_kwargs = kwargs
        return _FakeCurlResponse()

    async def head(self, **kwargs):
        type(self).last_method = 'head'
        type(self).last_kwargs = kwargs
        return _FakeCurlResponse()

@pytest.fixture
def fake_curl_cffi(monkeypatch):
    """Replace CurlCffiAsyncSession with a recorder. Resets capture between tests."""
    from maigret import checking
    _FakeCurlSession.last_method = None
    _FakeCurlSession.last_kwargs = None
    # Patch at the SUT's namespace.
    monkeypatch.setattr(checking, 'CurlCffiAsyncSession', _FakeCurlSession, raising=False)
    return _FakeCurlSession

# --- Tests ---

@pytest.mark.generated
@pytest.mark.happy_path
def test_prepare_sets_attributes():
    """Verify that prepare correctly assigns all its arguments to the corresponding instance attributes."""
    checker = CurlCffiChecker(logger=Mock())
    checker.prepare(
        url='https://example.com',
        headers={'X-Test': 'val'},
        allow_redirects=False,
        timeout=5,
        method='post',
        payload={'a': 1}
    )
    assert checker.url == 'https://example.com'
    assert checker.headers == {'X-Test': 'val'}
    assert checker.allow_redirects is False
    assert checker.timeout == 5
    assert checker.method == 'post'
    assert checker.payload == {'a': 1}

@pytest.mark.generated
@pytest.mark.happy_path
def test_prepare_integration_head_method(fake_curl_cffi):
    """Verify that calling prepare with method='head' results in a HEAD request being executed when check() is called."""
    checker = CurlCffiChecker(logger=Mock())
    checker.prepare(url='https://example.com', method='head')
    
    async def _t():
        await checker.check()
    
    asyncio.run(_t())
    
    assert fake_curl_cffi.last_method == 'head'

@pytest.mark.generated
@pytest.mark.happy_path
def test_prepare_integration_custom_timeout(fake_curl_cffi):
    """Verify that a non-zero timeout passed to prepare is correctly forwarded to the session in check()."""
    checker = CurlCffiChecker(logger=Mock())
    checker.prepare(url='https://example.com', timeout=7)
    
    async def _t():
        await checker.check()
        
    asyncio.run(_t())
    
    assert fake_curl_cffi.last_kwargs['timeout'] == 7

@pytest.mark.generated
@pytest.mark.edge_case
def test_prepare_integration_default_timeout(fake_curl_cffi):
    """Verify that the default timeout=0 in prepare is translated to a default of 10 seconds in the session call within check()."""
    checker = CurlCffiChecker(logger=Mock())
    checker.prepare(url='https://example.com', timeout=0)
    
    async def _t():
        await checker.check()
        
    asyncio.run(_t())
    
    assert fake_curl_cffi.last_kwargs['timeout'] == 10

@pytest.mark.generated
@pytest.mark.happy_path
def test_prepare_integration_disallow_redirects(fake_curl_cffi):
    """Verify that allow_redirects=False passed to prepare is correctly forwarded to the session in check()."""
    checker = CurlCffiChecker(logger=Mock())
    checker.prepare(url='https://example.com', allow_redirects=False)
    
    async def _t():
        await checker.check()
        
    asyncio.run(_t())
    
    assert fake_curl_cffi.last_kwargs['allow_redirects'] is False

@pytest.mark.generated
@pytest.mark.edge_case
def test_prepare_integration_method_case_insensitivity(fake_curl_cffi):
    """Verify that prepare handles uppercase method names correctly by ensuring check() performs the expected request type."""
    checker = CurlCffiChecker(logger=Mock())
    checker.prepare(url='https://example.com', method='POST')
    
    async def _t():
        await checker.check()
        
    asyncio.run(_t())
    
    assert fake_curl_cffi.last_method == 'post'
