# ROOST_METHOD_HASH=CurlCffiChecker.__init___4ed187de7e
# ROOST_METHOD_SIG_HASH=CurlCffiChecker.__init___dc2abf071b

"""Tests for `maigret.checking.CurlCffiChecker.__init__`.

Auto-generated by roost-pytest. Re-generate when the source
changes; see the run report for generation details.
"""
# Source: maigret/checking.py:225-233
# Scenarios:
#   - [happy_path] test_init_default_values: Verify that CurlCffiChecker initializes with correct default values when no arguments are provided.
#   - [happy_path] test_init_custom_kwargs: Verify that CurlCffiChecker correctly assigns logger and browser_emulate from keyword arguments.
#   - [edge_case] test_init_explicit_none: Verify that passing explicit None for logger and browser_emulate overrides the default values.
#   - [edge_case] test_init_accepts_positional_args: Verify that the constructor accepts positional arguments without error, even if they are currently ignored.

import sys
from unittest.mock import MagicMock

# Mock missing dependencies to allow importing maigret.checking
for module in [
    'aiodns', 'alive_progress', 'socid_extractor', 'python_socks',
    'colorama', 'aiohttp', 'aiohttp.client_exceptions', 'curl_cffi',
    'curl_cffi.requests', 'xmind', 'jinja2', 'pandas', 'openpyxl',
    'cloudscraper', 'requests'
]:
    sys.modules[module] = MagicMock()

# Special handling for some mocks
sys.modules['aiodns'].error.DNSError = type('DNSError', (Exception,), {})

import pytest
from unittest.mock import Mock
from maigret.checking import CurlCffiChecker

@pytest.mark.generated
@pytest.mark.happy_path
def test_init_default_values():
    """Verify that CurlCffiChecker initializes with correct default values when no arguments are provided."""
    checker = CurlCffiChecker()
    assert checker.browser_emulate == 'chrome'
    assert checker.url is None
    assert checker.headers is None
    assert checker.allow_redirects is True
    assert checker.timeout == 0
    assert checker.method == 'get'
    assert checker.payload is None
    assert hasattr(checker.logger, 'debug')

@pytest.mark.generated
@pytest.mark.happy_path
def test_init_custom_kwargs():
    """Verify that CurlCffiChecker correctly assigns logger and browser_emulate from keyword arguments."""
    custom_logger = Mock()
    checker = CurlCffiChecker(logger=custom_logger, browser_emulate='firefox')
    assert checker.logger == custom_logger
    assert checker.browser_emulate == 'firefox'

@pytest.mark.generated
@pytest.mark.edge_case
def test_init_explicit_none():
    """Verify that passing explicit None for logger and browser_emulate overrides the default values."""
    checker = CurlCffiChecker(logger=None, browser_emulate=None)
    assert checker.logger is None
    assert checker.browser_emulate is None

@pytest.mark.generated
@pytest.mark.edge_case
def test_init_accepts_positional_args():
    """Verify that the constructor accepts positional arguments without error, even if they are currently ignored."""
    checker = CurlCffiChecker("positional_arg", key="value")
    assert checker.url is None
    assert checker.method == 'get'
