# ROOST_METHOD_HASH=check_25d426ea3f
# ROOST_METHOD_SIG_HASH=check_7cf19bb4aa

"""Tests for `maigret.checking.SimpleAiohttpChecker.check`.

Auto-generated by roost-pytest. Re-generate when the source
changes; see the run report for generation details.
"""
# Source: maigret/checking.py:137-173
# Scenarios:
#   - [happy_path] happy_path_get: Verify a standard GET request returns the expected content and status code.
#   - [happy_path] post_json_payload: Verify a POST request with a dictionary payload sends JSON by default.
#   - [happy_path] post_form_payload: Verify a POST request with form-urlencoded header sends form data.
#   - [error_path] request_timeout: Verify that a timeout during the request returns a CheckError of type 'Request timeout'.
#   - [error_path] connection_failure: Verify that a connection failure returns a CheckError of type 'Connecting failure'.
#   - [happy_path] proxy_connector_setup: Verify that providing a proxy URL results in the initialization of ProxyConnector with that URL.

import sys
import asyncio
from unittest.mock import MagicMock, patch, AsyncMock

# Mock missing dependencies before importing maigret
class MockProxyError(Exception): pass
proxy_errors = MagicMock()
proxy_errors.ProxyError = MockProxyError
sys.modules['python_socks'] = MagicMock()
sys.modules['python_socks._errors'] = proxy_errors

sys.modules['aiodns'] = MagicMock()
sys.modules['aiohttp_socks'] = MagicMock()
sys.modules['alive_progress'] = MagicMock()
sys.modules['socid_extractor'] = MagicMock()
sys.modules['colorama'] = MagicMock()
sys.modules['xmind'] = MagicMock()
sys.modules['jinja2'] = MagicMock()
sys.modules['cloudscraper'] = MagicMock()
sys.modules['curl_cffi'] = MagicMock()
sys.modules['curl_cffi.requests'] = MagicMock()

import pytest
from maigret.checking import SimpleAiohttpChecker
from maigret.errors import CheckError
from aiohttp.client_exceptions import ClientConnectorError

@pytest.mark.generated
@pytest.mark.happy_path
def test_happy_path_get():
    """Verify a standard GET request returns the expected content and status code."""
    async def _t():
        checker = SimpleAiohttpChecker()
        url = "http://example.com/test"
        checker.prepare(url=url)
        
        mock_response = MagicMock()
        mock_response.status = 200
        mock_response.content.read = AsyncMock(return_value=b"success content")
        mock_response.charset = "utf-8"
        mock_response.__aenter__ = AsyncMock(return_value=mock_response)
        mock_response.__aexit__ = AsyncMock()
        
        with patch("maigret.checking.ClientSession") as mock_session_cls:
            mock_session = MagicMock()
            mock_session_cls.return_value.__aenter__ = AsyncMock(return_value=mock_session)
            mock_session_cls.return_value.__aexit__ = AsyncMock()
            mock_session.get.return_value = mock_response
            
            result = await checker.check()
            
        assert result == ("success content", 200, None)
    
    asyncio.run(_t())

@pytest.mark.generated
@pytest.mark.happy_path
def test_post_json_payload():
    """Verify a POST request with a dictionary payload sends JSON by default."""
    async def _t():
        checker = SimpleAiohttpChecker()
        url = "http://example.com/post"
        payload = {"key": "value"}
        checker.prepare(url=url, method="post", payload=payload)
        
        mock_response = MagicMock()
        mock_response.status = 200
        mock_response.content.read = AsyncMock(return_value=b"ok")
        mock_response.charset = "utf-8"
        mock_response.__aenter__ = AsyncMock(return_value=mock_response)
        mock_response.__aexit__ = AsyncMock()
        
        with patch("maigret.checking.ClientSession") as mock_session_cls:
            mock_session = MagicMock()
            mock_session_cls.return_value.__aenter__ = AsyncMock(return_value=mock_session)
            mock_session_cls.return_value.__aexit__ = AsyncMock()
            mock_session.post.return_value = mock_response
            
            result = await checker.check()
            
            # Verify it was called with json=payload
            mock_session.post.assert_called()
            args, kwargs = mock_session.post.call_args
            assert kwargs['json'] == payload
            
        assert result == ("ok", 200, None)
        
    asyncio.run(_t())

@pytest.mark.generated
@pytest.mark.happy_path
def test_post_form_payload():
    """Verify a POST request with form-urlencoded header sends form data."""
    async def _t():
        checker = SimpleAiohttpChecker()
        url = "http://example.com/post-form"
        payload = {"key": "value"}
        headers = {"Content-Type": "application/x-www-form-urlencoded"}
        checker.prepare(url=url, method="post", payload=payload, headers=headers)
        
        mock_response = MagicMock()
        mock_response.status = 200
        mock_response.content.read = AsyncMock(return_value=b"ok")
        mock_response.charset = "utf-8"
        mock_response.__aenter__ = AsyncMock(return_value=mock_response)
        mock_response.__aexit__ = AsyncMock()
        
        with patch("maigret.checking.ClientSession") as mock_session_cls:
            mock_session = MagicMock()
            mock_session_cls.return_value.__aenter__ = AsyncMock(return_value=mock_session)
            mock_session_cls.return_value.__aexit__ = AsyncMock()
            mock_session.post.return_value = mock_response
            
            result = await checker.check()
            
            # Verify it was called with data=payload
            mock_session.post.assert_called()
            args, kwargs = mock_session.post.call_args
            assert kwargs['data'] == payload
            
        assert result == ("ok", 200, None)
        
    asyncio.run(_t())

@pytest.mark.generated
@pytest.mark.error_path
def test_request_timeout():
    """Verify that a timeout during the request returns a CheckError of type 'Request timeout'."""
    async def _t():
        checker = SimpleAiohttpChecker()
        checker.prepare(url="http://example.com/timeout", timeout=0.001)
        
        with patch("maigret.checking.ClientSession") as mock_session_cls:
            mock_session = MagicMock()
            mock_session_cls.return_value.__aenter__ = AsyncMock(return_value=mock_session)
            mock_session_cls.return_value.__aexit__ = AsyncMock()
            mock_session.get.side_effect = asyncio.TimeoutError()
            
            result = await checker.check()
            
        assert result[0] == ""
        assert result[1] == 0
        assert result[2].type == "Request timeout"
        
    asyncio.run(_t())

@pytest.mark.generated
@pytest.mark.error_path
def test_connection_failure():
    """Verify that a connection failure returns a CheckError of type 'Connecting failure'."""
    async def _t():
        checker = SimpleAiohttpChecker()
        checker.prepare(url="http://nonexistent.domain.example.com")
        
        with patch("maigret.checking.ClientSession") as mock_session_cls:
            mock_session = MagicMock()
            mock_session_cls.return_value.__aenter__ = AsyncMock(return_value=mock_session)
            mock_session_cls.return_value.__aexit__ = AsyncMock()
            # ClientConnectorError needs connection_key and os_error
            mock_session.get.side_effect = ClientConnectorError(MagicMock(), MagicMock())
            
            result = await checker.check()
        
        assert result[1] == 0
        assert result[2].type == "Connecting failure"
        
    asyncio.run(_t())

@pytest.mark.generated
@pytest.mark.happy_path
def test_proxy_connector_setup():
    """Verify that providing a proxy URL results in the initialization of ProxyConnector with that URL."""
    async def _t():
        proxy_url = "http://user:pass@proxy:8080"
        checker = SimpleAiohttpChecker(proxy=proxy_url)
        checker.prepare(url="http://example.com")
        
        mock_connector = MagicMock()
        # ProxyConnector is imported inside check() from aiohttp_socks
        with patch("aiohttp_socks.ProxyConnector.from_url", return_value=mock_connector) as mock_from_url:
            # Mock ClientSession to avoid actual network calls and use our mock connector
            with patch("maigret.checking.ClientSession") as mock_session_cls:
                mock_session = MagicMock()
                mock_session_cls.return_value.__aenter__ = AsyncMock(return_value=mock_session)
                mock_session_cls.return_value.__aexit__ = AsyncMock()
                # Mock _make_request to return a dummy success result
                with patch.object(SimpleAiohttpChecker, "_make_request", return_value=("ok", 200, None)):
                    await checker.check()
        
        mock_from_url.assert_called_with(proxy_url)
        
    asyncio.run(_t())
