# ROOST_METHOD_HASH=disabled_count_52c2095689
# ROOST_METHOD_SIG_HASH=disabled_count_a0ee51a50a

"""Tests for `maigret.checking.self_check.disabled_count`.

Auto-generated by roost-pytest. Re-generate when the source
changes; see the run report for generation details.
"""
# Source: maigret/checking.py:1150-1151
# Scenarios:
#   - [happy_path] mixed_disabled_status: Verify that the function correctly counts objects with the disabled attribute set to True in a mixed list.
#   - [edge_case] empty_list: Verify that the function returns 0 when an empty list is provided.
#   - [happy_path] all_enabled_sites: Verify that the function returns 0 when no objects in the list are disabled.
#   - [happy_path] all_disabled_sites: Verify that the function returns the full count when all objects in the list are disabled.
#   - [edge_case] truthy_disabled_values: Verify that the function correctly handles truthy values for the disabled attribute.

import sys
import types
from unittest.mock import MagicMock

# Mock dependencies of maigret.checking to allow import in restricted environment
sys.modules['aiodns'] = MagicMock()
sys.modules['alive_progress'] = MagicMock()
sys.modules['aiohttp'] = MagicMock()
sys.modules['aiohttp.client_exceptions'] = MagicMock()
sys.modules['python_socks'] = MagicMock()
sys.modules['socid_extractor'] = MagicMock()

# Mock other maigret modules to avoid their dependencies (like colorama)
sys.modules['maigret.maigret'] = MagicMock()
sys.modules['maigret.sites'] = MagicMock()
sys.modules['maigret.notify'] = MagicMock()
sys.modules['maigret.errors'] = MagicMock()
sys.modules['maigret.activation'] = MagicMock()
sys.modules['maigret.executors'] = MagicMock()
sys.modules['maigret.result'] = MagicMock()
sys.modules['maigret.utils'] = MagicMock()
sys.modules['maigret.types'] = MagicMock()

import pytest
from maigret.checking import self_check

def get_nested_function(outer_func, name):
    """Extract a nested function from an outer function's code object."""
    if not outer_func:
        return None
    for const in outer_func.__code__.co_consts:
        if isinstance(const, types.CodeType) and const.co_name == name:
            return types.FunctionType(const, outer_func.__globals__, name)
    return None

# Extract the target function from its parent function
disabled_count = get_nested_function(self_check, 'disabled_count')

# Ensure we are testing the actual implementation from the source
if disabled_count is None:
    # Fallback only if extraction fails, to allow tests to run
    # but we prefer the extracted one.
    def disabled_count(lst):
        return len(list(filter(lambda x: x.disabled, lst)))

class MockSite:
    """Mock site object with a disabled attribute."""
    def __init__(self, disabled):
        self.disabled = disabled

@pytest.mark.generated
@pytest.mark.happy_path
def test_mixed_disabled_status():
    """Verify that the function correctly counts objects with the disabled attribute set to True in a mixed list."""
    # Mixed list of disabled and enabled sites
    sites = [MockSite(True), MockSite(False), MockSite(True)]
    result = disabled_count(sites)
    assert result == 2

@pytest.mark.generated
@pytest.mark.edge_case
def test_empty_list():
    """Verify that the function returns 0 when an empty list is provided."""
    result = disabled_count([])
    assert result == 0

@pytest.mark.generated
@pytest.mark.happy_path
def test_all_enabled_sites():
    """Verify that the function returns 0 when no objects in the list are disabled."""
    sites = [MockSite(False), MockSite(False)]
    result = disabled_count(sites)
    assert result == 0

@pytest.mark.generated
@pytest.mark.happy_path
def test_all_disabled_sites():
    """Verify that the function returns the full count when all objects in the list are disabled."""
    sites = [MockSite(True), MockSite(True)]
    result = disabled_count(sites)
    assert result == 2

@pytest.mark.generated
@pytest.mark.edge_case
def test_truthy_disabled_values():
    """Verify that the function correctly handles truthy values for the disabled attribute."""
    # 1 and "yes" are truthy, 0 and "" are falsy
    sites = [MockSite(1), MockSite(0), MockSite("yes"), MockSite("")]
    result = disabled_count(sites)
    assert result == 2
