# ROOST_METHOD_HASH=_make_request_7a206b47b4
# ROOST_METHOD_SIG_HASH=_make_request_682703705a

"""Tests for `maigret.checking.SimpleAiohttpChecker._make_request`.

Auto-generated by roost-pytest. Re-generate when the source
changes; see the run report for generation details.
"""
# Source: maigret/checking.py:79-135
# Scenarios:
#   - [happy_path] happy_path_get: Verify a successful GET request returns the decoded content and status code.
#   - [happy_path] happy_path_post_json: Verify a POST request with a payload defaults to sending it as JSON.
#   - [happy_path] happy_path_post_form_urlencoded: Verify a POST request with form-urlencoded Content-Type sends payload as data.
#   - [edge_case] edge_case_status_zero: Verify that a status code of 0 is treated as a 'Connection lost' error.
#   - [error_path] error_path_timeout: Verify that asyncio.TimeoutError is caught and returned as a CheckError.
#   - [error_path] error_path_ssl_error: Verify that ssl.SSLError is caught and returned as an SSL CheckError.

import sys
from unittest.mock import MagicMock

# Mock missing dependencies before importing maigret.checking
class MockException(Exception):
    pass

# Mock python_socks and its ProxyError exception
proxy_errors_mock = MagicMock()
proxy_errors_mock.ProxyError = MockException

sys.modules['aiodns'] = MagicMock()
sys.modules['alive_progress'] = MagicMock()
sys.modules['socid_extractor'] = MagicMock()
sys.modules['aiohttp_socks'] = MagicMock()
sys.modules['python_socks'] = MagicMock()
sys.modules['python_socks._errors'] = proxy_errors_mock
sys.modules['colorama'] = MagicMock()
sys.modules['xmind'] = MagicMock()
sys.modules['jinja2'] = MagicMock()
sys.modules['requests'] = MagicMock()
sys.modules['bs4'] = MagicMock()
sys.modules['cloudscraper'] = MagicMock()

# Mock aiohttp and its exceptions
aiohttp_mock = MagicMock()
aiohttp_mock.http_exceptions = MagicMock()
aiohttp_mock.http_exceptions.BadHttpMessage = MockException
aiohttp_mock.ClientSession = MagicMock()
aiohttp_mock.TCPConnector = MagicMock()
sys.modules['aiohttp'] = aiohttp_mock

aiohttp_client_exceptions_mock = MagicMock()
aiohttp_client_exceptions_mock.ClientConnectorError = MockException
aiohttp_client_exceptions_mock.ServerDisconnectedError = MockException
sys.modules['aiohttp.client_exceptions'] = aiohttp_client_exceptions_mock

import asyncio
import ssl
import pytest
from unittest.mock import AsyncMock, Mock
import maigret.checking
from maigret.checking import SimpleAiohttpChecker
from maigret.errors import CheckError

# Ensure caught classes are exception classes in the loaded module
maigret.checking.proxy_errors.ProxyError = MockException
maigret.checking.ClientConnectorError = MockException
maigret.checking.ServerDisconnectedError = MockException
maigret.checking.http_exceptions.BadHttpMessage = MockException

@pytest.mark.generated
@pytest.mark.happy_path
def test_happy_path_get():
    """Verify a successful GET request returns the decoded content and status code."""
    async def _t():
        session = MagicMock()
        response = AsyncMock()
        cm = AsyncMock()
        session.get.return_value = cm
        cm.__aenter__.return_value = response
        
        response.status = 200
        response.content.read.return_value = b"content"
        response.charset = "utf-8"
        
        logger = Mock()
        checker = SimpleAiohttpChecker()
        
        result = await checker._make_request(
            session, "http://example.com", {"User-Agent": "test"}, True, 10, "get", logger
        )
        
        assert result[2] is None, f"Unexpected error: {result[2].desc if result[2] else ''}"
        assert result == ("content", 200, None)
        session.get.assert_called_once_with(
            url="http://example.com",
            headers={"User-Agent": "test"},
            allow_redirects=True,
            timeout=10
        )
        logger.debug.assert_called_with("content")

    asyncio.run(_t())

@pytest.mark.generated
@pytest.mark.happy_path
def test_happy_path_post_json():
    """Verify a POST request with a payload defaults to sending it as JSON."""
    async def _t():
        session = MagicMock()
        response = AsyncMock()
        cm = AsyncMock()
        session.post.return_value = cm
        cm.__aenter__.return_value = response
        
        response.status = 201
        response.content.read.return_value = b""
        response.charset = "utf-8"
        
        logger = Mock()
        checker = SimpleAiohttpChecker()
        
        payload = {"key": "value"}
        result = await checker._make_request(
            session, "http://example.com", {}, True, 10, "post", logger, payload=payload
        )
        
        assert result[2] is None, f"Unexpected error: {result[2].desc if result[2] else ''}"
        session.post.assert_called_with(
            url="http://example.com",
            headers={},
            allow_redirects=True,
            timeout=10,
            json=payload
        )

    asyncio.run(_t())

@pytest.mark.generated
@pytest.mark.happy_path
def test_happy_path_post_form_urlencoded():
    """Verify a POST request with form-urlencoded Content-Type sends payload as data."""
    async def _t():
        session = MagicMock()
        response = AsyncMock()
        cm = AsyncMock()
        session.post.return_value = cm
        cm.__aenter__.return_value = response
        
        response.status = 200
        response.content.read.return_value = b""
        response.charset = "utf-8"
        
        logger = Mock()
        checker = SimpleAiohttpChecker()
        
        headers = {"Content-Type": "application/x-www-form-urlencoded"}
        payload = "key=value"
        result = await checker._make_request(
            session, "http://example.com", headers, True, 10, "post", logger, payload=payload
        )
        
        assert result[2] is None, f"Unexpected error: {result[2].desc if result[2] else ''}"
        session.post.assert_called_with(
            url="http://example.com",
            headers=headers,
            allow_redirects=True,
            timeout=10,
            data=payload
        )

    asyncio.run(_t())

@pytest.mark.generated
@pytest.mark.edge_case
def test_edge_case_status_zero():
    """Verify that a status code of 0 is treated as a 'Connection lost' error."""
    async def _t():
        session = MagicMock()
        response = AsyncMock()
        cm = AsyncMock()
        session.get.return_value = cm
        cm.__aenter__.return_value = response
        
        response.status = 0
        response.content.read.return_value = b""
        response.charset = "utf-8"
        
        logger = Mock()
        checker = SimpleAiohttpChecker()
        
        result = await checker._make_request(
            session, "http://example.com", {}, True, 10, "get", logger
        )
        
        assert result[1] == 0
        assert isinstance(result[2], CheckError)
        assert result[2].type == "Connection lost"

    asyncio.run(_t())

@pytest.mark.generated
@pytest.mark.error_path
def test_error_path_timeout():
    """Verify that asyncio.TimeoutError is caught and returned as a CheckError."""
    async def _t():
        session = MagicMock()
        session.get.side_effect = asyncio.TimeoutError("timeout")
        
        logger = Mock()
        checker = SimpleAiohttpChecker()
        
        result = await checker._make_request(
            session, "http://example.com", {}, True, 10, "get", logger
        )
        
        assert result[0] is None
        assert result[1] == 0
        assert isinstance(result[2], CheckError)
        assert result[2].type == "Request timeout"

    asyncio.run(_t())

@pytest.mark.generated
@pytest.mark.error_path
def test_error_path_ssl_error():
    """Verify that ssl.SSLError is caught and returned as an SSL CheckError."""
    async def _t():
        session = MagicMock()
        session.get.side_effect = ssl.SSLError("ssl error")
        
        logger = Mock()
        checker = SimpleAiohttpChecker()
        
        result = await checker._make_request(
            session, "http://example.com", {}, True, 10, "get", logger
        )
        
        assert result[2].type == "SSL"
        assert "ssl error" in result[2].desc

    asyncio.run(_t())
