# ROOST_METHOD_HASH=check_3f275b758f
# ROOST_METHOD_SIG_HASH=check_7cf19bb4aa

"""Tests for `maigret.checking.CheckerMock.check`.

Auto-generated by roost-pytest. Re-generate when the source
changes; see the run report for generation details.
"""
# Source: maigret/checking.py:297-299
# Scenarios:
#   - [happy_path] test_check_returns_defaults: Verify that the check method returns the expected default values (empty string, status code 0, and no error).
#   - [happy_path] test_check_is_async: Verify that the check method is an asynchronous function (returns a coroutine).
#   - [edge_case] test_check_after_prepare: Verify that calling prepare with arguments does not affect the output of the check method.
#   - [happy_path] test_check_multiple_calls: Verify that multiple calls to the check method return consistent results.
#   - [edge_case] test_check_with_init_args: Verify that the checker can be instantiated with arbitrary arguments and still functions correctly.

import sys
from unittest.mock import MagicMock

# Mock missing dependencies before importing maigret.checking
sys.modules['aiodns'] = MagicMock()
sys.modules['alive_progress'] = MagicMock()
sys.modules['python_socks'] = MagicMock()
sys.modules['socid_extractor'] = MagicMock()
sys.modules['colorama'] = MagicMock()
sys.modules['xmind'] = MagicMock()
sys.modules['jinja2'] = MagicMock()
sys.modules['cloudscraper'] = MagicMock()

import asyncio
import pytest
from maigret.checking import CheckerMock

@pytest.mark.generated
@pytest.mark.happy_path
def test_check_returns_defaults():
    """Verify that the check method returns the expected default values (empty string, status code 0, and no error)."""
    async def _t():
        checker = CheckerMock()
        result = await checker.check()
        assert result == ('', 0, None)
    
    asyncio.run(_t())

@pytest.mark.generated
@pytest.mark.happy_path
def test_check_is_async():
    """Verify that the check method is an asynchronous function (returns a coroutine)."""
    checker = CheckerMock()
    coro = checker.check()
    assert asyncio.iscoroutine(coro) is True
    
    async def _t():
        await coro
        
    asyncio.run(_t())

@pytest.mark.generated
@pytest.mark.edge_case
def test_check_after_prepare():
    """Verify that calling prepare with arguments does not affect the output of the check method."""
    async def _t():
        checker = CheckerMock()
        checker.prepare('https://example.com', timeout=10)
        result = await checker.check()
        assert result == ('', 0, None)
        
    asyncio.run(_t())

@pytest.mark.generated
@pytest.mark.happy_path
def test_check_multiple_calls():
    """Verify that multiple calls to the check method return consistent results."""
    async def _t():
        checker = CheckerMock()
        res1 = await checker.check()
        res2 = await checker.check()
        assert res1 == res2 == ('', 0, None)
        
    asyncio.run(_t())

@pytest.mark.generated
@pytest.mark.edge_case
def test_check_with_init_args():
    """Verify that the checker can be instantiated with arbitrary arguments and still functions correctly."""
    async def _t():
        checker = CheckerMock(some_arg=1, another_arg='test')
        result = await checker.check()
        assert result == ('', 0, None)
        
    asyncio.run(_t())
